import type { PublicUser, PublicListing, PublicReview } from './types';

export const MOCK_PUBLIC_USER: PublicUser = {
  id: 'u-042',
  fullName: 'Алексей Иванов',
  nickname: 'alex_rent',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
  bio: 'Сдаю технику, инструменты и спортивное оборудование в аренду по Новосибирску. Всё проверено перед каждой выдачей, поддерживаю идеальное состояние. Выдача и возврат — в день обращения. Есть доставка по городу.',
  rating: 4.9,
  reviewCount: 87,
  memberSince: '2023-08-12',
  city: 'Новосибирск',
  isVerified: true,
  responseTime: '~15 мин',
  responseRate: 98,
  completedDeals: 134,
  activeListings: 12,
  lastOnline: 'Онлайн',
  languages: ['Русский', 'English'],
  trustLevel: 'super',
};

export const MOCK_PUBLIC_LISTINGS: PublicListing[] = [
  {
    id: 'p-001',
    title: 'Перфоратор Bosch GBH 2-28',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=300&fit=crop',
    category: 'Инструменты',
    pricePerDay: '600',
    isAvailable: true,
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: 'p-002',
    title: 'Шуруповёрт Makita DDF484',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&h=300&fit=crop',
    category: 'Инструменты',
    pricePerDay: '450',
    isAvailable: true,
    rating: 5.0,
    reviewCount: 9,
  },
  {
    id: 'p-003',
    title: 'Проектор Epson EH-TW7100',
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=300&fit=crop',
    category: 'Электроника',
    pricePerDay: '1800',
    isAvailable: true,
    rating: 4.9,
    reviewCount: 7,
  },
  {
    id: 'p-004',
    title: 'Велосипед Trek Marlin 7',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=300&fit=crop',
    category: 'Спорт',
    pricePerDay: '800',
    isAvailable: true,
    rating: 4.7,
    reviewCount: 12,
  },
  {
    id: 'p-005',
    title: 'Генератор Honda EU22i',
    image: 'https://images.unsplash.com/photo-1611606063065-ee7946f0787a?w=400&h=300&fit=crop',
    category: 'Техника',
    pricePerDay: '2400',
    isAvailable: false,
    rating: 4.7,
    reviewCount: 6,
  },
  {
    id: 'p-006',
    title: 'Мойка высокого давления Karcher K5',
    image: 'https://images.unsplash.com/photo-1621274147744-cfb5694bb233?w=400&h=300&fit=crop',
    category: 'Для дома',
    pricePerDay: '900',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 8,
  },
  {
    id: 'p-007',
    title: 'Палатка Nordisk Asgard 12.6',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&h=300&fit=crop',
    category: 'Туризм',
    pricePerDay: '1500',
    isAvailable: true,
    rating: 5.0,
    reviewCount: 3,
  },
  {
    id: 'p-008',
    title: 'Дрон DJI Mavic Air 2',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&h=300&fit=crop',
    category: 'Электроника',
    pricePerDay: '3500',
    isAvailable: true,
    rating: 4.9,
    reviewCount: 5,
  },
  {
    id: 'p-009',
    title: 'Лазерный уровень Bosch GLL 3-80',
    image: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=400&h=300&fit=crop',
    category: 'Инструменты',
    pricePerDay: '700',
    isAvailable: true,
    rating: 5.0,
    reviewCount: 4,
  },
  {
    id: 'p-010',
    title: 'SUP-борд Aqua Marina',
    image: 'https://images.unsplash.com/photo-1526188717906-ab4a2f949f7d?w=400&h=300&fit=crop',
    category: 'Спорт',
    pricePerDay: '1200',
    isAvailable: false,
    rating: 4.8,
    reviewCount: 10,
  },
];

export const MOCK_PUBLIC_REVIEWS: PublicReview[] = [
  {
    id: 'r-001',
    authorName: 'Владислав П.',
    authorAvatar: null,
    rating: 5,
    text: 'Отличный перфоратор, забрал за 10 минут. Алексей пунктуальный, вещь в идеальном состоянии. Всё объяснил, дал свёрла в комплекте. Однозначно рекомендую!',
    date: '2025-04-15',
    itemTitle: 'Перфоратор Bosch GBH 2-28',
  },
  {
    id: 'r-002',
    authorName: 'Мария С.',
    authorAvatar: null,
    rating: 5,
    text: 'Брали генератор на выходные за город. Работает идеально, тихий, экономичный. Алексей подробно объяснил все нюансы эксплуатации и даже канистру бензина дал в подарок. Спасибо огромное!',
    date: '2025-04-10',
    itemTitle: 'Генератор Honda EU22i',
  },
  {
    id: 'r-003',
    authorName: 'Дмитрий К.',
    authorAvatar: null,
    rating: 4,
    text: 'Шуруповёрт хороший, аккумулятор держит весь день активной работы. Единственное — чехол немного потрёпан, но на работу не влияет. В целом доволен.',
    date: '2025-03-28',
    itemTitle: 'Шуруповёрт Makita DDF484',
  },
  {
    id: 'r-004',
    authorName: 'Елена В.',
    authorAvatar: null,
    rating: 5,
    text: 'Уже третий раз арендую у Алексея. Всегда всё чисто, исправно, на связи 24/7. Лучший арендодатель на платформе. В этот раз брали проектор на день рождения — все были в восторге!',
    date: '2025-03-20',
    itemTitle: 'Проектор Epson EH-TW7100',
  },
  {
    id: 'r-005',
    authorName: 'Олег С.',
    authorAvatar: null,
    rating: 5,
    text: 'Мойка отработала на ура. Помыл машину, террасу и садовую мебель. Алексей доставил сам, забрал тоже — сервис на высоте. Обязательно обращусь ещё.',
    date: '2025-03-12',
    itemTitle: 'Мойка высокого давления Karcher K5',
  },
  {
    id: 'r-006',
    authorName: 'Анна Т.',
    authorAvatar: null,
    rating: 5,
    text: 'Арендовали дрон для свадебной съёмки. Состояние идеальное, все аксессуары в комплекте. Алексей даже показал как управлять. Фотографии получились космические!',
    date: '2025-02-28',
    itemTitle: 'Дрон DJI Mavic Air 2',
  },
  {
    id: 'r-007',
    authorName: 'Игорь М.',
    authorAvatar: null,
    rating: 5,
    text: 'Брали велосипед на неделю для поездок по городу. Trek в отличном состоянии, всё настроено, колёса накачаны. Забрал и поехал. Цена более чем адекватная.',
    date: '2025-02-15',
    itemTitle: 'Велосипед Trek Marlin 7',
  },
  {
    id: 'r-008',
    authorName: 'Светлана Р.',
    authorAvatar: null,
    rating: 4,
    text: 'Палатка отличная, вместительная. Брали на 3 дня в поход. Небольшой минус — в комплекте не было дополнительных колышков, но это мелочь. Алексей всегда на связи.',
    date: '2025-02-01',
    itemTitle: 'Палатка Nordisk Asgard 12.6',
  },
];
