import type { PublicUser, PublicListing, PublicReview } from './types';

export const MOCK_PUBLIC_USER: PublicUser = {
  id: 'u-042',
  full_name: 'Алексей Иванов',
  nickname: 'alex_rent',
  avatar_url: null,
  bio: 'Сдаю строительный инструмент и технику для ремонта. Всё проверено, выдача в день обращения. Работаю по всему Новосибирску.',
  rating: 4.9,
  reviewCount: 87,
  memberSince: '2023-08-12',
  city: 'Новосибирск',
  isVerified: true,
  responseTime: '~15 мин',
  responseRate: 98,
  completedDeals: 134,
  activeListings: 12,
};

export const MOCK_PUBLIC_LISTINGS: PublicListing[] = [
  {
    id: 'p-001',
    title: 'Перфоратор Bosch GBH 2-28',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
    category: 'Инструменты',
    pricePerDay: '600',
    isAvailable: true,
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: 'p-002',
    title: 'Шуруповёрт Makita DDF484',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400',
    category: 'Инструменты',
    pricePerDay: '450',
    isAvailable: true,
    rating: 5.0,
    reviewCount: 9,
  },
  {
    id: 'p-003',
    title: 'Генератор Honda EU22i',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    category: 'Инструменты',
    pricePerDay: '2400',
    isAvailable: false,
    rating: 4.7,
    reviewCount: 6,
  },
  {
    id: 'p-004',
    title: 'Бетономешалка 180 л',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
    category: 'Инструменты',
    pricePerDay: '1200',
    isAvailable: true,
    rating: 4.9,
    reviewCount: 11,
  },
  {
    id: 'p-005',
    title: 'Лазерный уровень Bosch GLL 3-80',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400',
    category: 'Инструменты',
    pricePerDay: '700',
    isAvailable: true,
    rating: 5.0,
    reviewCount: 4,
  },
  {
    id: 'p-006',
    title: 'Мойка высокого давления Karcher K5',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    category: 'Для дома',
    pricePerDay: '900',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 8,
  },
];

export const MOCK_PUBLIC_REVIEWS: PublicReview[] = [
  {
    id: 'r-001',
    authorName: 'Владислав П.',
    authorAvatar: null,
    rating: 5,
    text: 'Отличный перфоратор, забрал за 10 минут. Алексей пунктуальный, вещь в идеальном состоянии. Рекомендую!',
    date: '2025-04-15',
    itemTitle: 'Перфоратор Bosch GBH 2-28',
  },
  {
    id: 'r-002',
    authorName: 'Мария С.',
    authorAvatar: null,
    rating: 5,
    text: 'Брали генератор на выходные за город. Работает идеально, всё объяснил по эксплуатации. Спасибо!',
    date: '2025-04-10',
    itemTitle: 'Генератор Honda EU22i',
  },
  {
    id: 'r-003',
    authorName: 'Дмитрий К.',
    authorAvatar: null,
    rating: 4,
    text: 'Шуруповёрт хороший, аккумулятор держит весь день. Единственное — чехол немного потрёпан, но на работу не влияет.',
    date: '2025-03-28',
    itemTitle: 'Шуруповёрт Makita DDF484',
  },
  {
    id: 'r-004',
    authorName: 'Елена В.',
    authorAvatar: null,
    rating: 5,
    text: 'Уже третий раз арендую у Алексея. Всегда всё чисто, исправно, на связи 24/7. Лучший арендодатель на платформе.',
    date: '2025-03-20',
    itemTitle: 'Лазерный уровень Bosch GLL 3-80',
  },
  {
    id: 'r-005',
    authorName: 'Олег С.',
    authorAvatar: null,
    rating: 5,
    text: 'Мойка отработала на ура. Помыл машину и террасу. Доставил сам, забрал тоже — сервис на высоте.',
    date: '2025-03-12',
    itemTitle: 'Мойка высокого давления Karcher K5',
  },
];
