import type { NotificationItem } from './types';

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  /* ═══ Сделки ═══ */
  {
    id: 'ntf-001',
    type: 'deal_request',
    priority: 'high',
    title: 'Новая заявка на аренду',
    body: 'Мария Иванова хочет арендовать «Canon EOS R5» на 3 дня (25–28 июля). Подтвердите или отклоните заявку.',
    createdAt: '2025-07-24T14:30:00Z',
    isRead: false,
    actionUrl: '/dev-ui/chat',
    actionLabel: 'Открыть чат',
    image: null,
    meta: {
      itemTitle: 'Canon EOS R5',
      counterpartyName: 'Мария Иванова',
      dealStatus: 'PENDING',
      dealStatusLabel: 'Ожидает подтверждения',
      amount: 4500,
      currency: '₽',
    },
  },
  {
    id: 'ntf-002',
    type: 'deal_confirmed',
    priority: 'normal',
    title: 'Заявка подтверждена',
    body: 'Алексей Петров подтвердил аренду «DJI Mavic 3 Pro». Аренда начинается 26 июля.',
    createdAt: '2025-07-24T12:15:00Z',
    isRead: false,
    actionUrl: '/dev-ui/chat',
    actionLabel: 'Перейти к сделке',
    image: null,
    meta: {
      itemTitle: 'DJI Mavic 3 Pro',
      counterpartyName: 'Алексей Петров',
      dealStatus: 'CONFIRMED',
      dealStatusLabel: 'Подтверждена',
      amount: 3500,
      currency: '₽',
    },
  },
  {
    id: 'ntf-003',
    type: 'deal_started',
    priority: 'normal',
    title: 'Аренда началась',
    body: 'Аренда «PlayStation 5 + VR2» с Дмитрием Козловым началась. Вещь передана арендатору.',
    createdAt: '2025-07-24T10:00:00Z',
    isRead: true,
    actionUrl: '/dev-ui/chat',
    image: null,
    meta: {
      itemTitle: 'PlayStation 5 + VR2',
      counterpartyName: 'Дмитрий Козлов',
      dealStatus: 'ACTIVE',
      dealStatusLabel: 'Активна',
    },
  },
  {
    id: 'ntf-004',
    type: 'deal_ending',
    priority: 'high',
    title: 'Аренда заканчивается завтра',
    body: 'Аренда «Шуруповёрт Makita DDF484» с Ольгой Смирновой заканчивается завтра, 25 июля. Договоритесь о возврате.',
    createdAt: '2025-07-24T08:00:00Z',
    isRead: false,
    actionUrl: '/dev-ui/chat',
    actionLabel: 'Написать сообщение',
    image: null,
    meta: {
      itemTitle: 'Шуруповёрт Makita DDF484',
      counterpartyName: 'Ольга Смирнова',
      dealStatus: 'ACTIVE',
      dealStatusLabel: 'Активна',
    },
  },
  {
    id: 'ntf-005',
    type: 'deal_completed',
    priority: 'low',
    title: 'Аренда завершена',
    body: 'Аренда «Велосипед Trek Marlin 7» с Сергеем Волковым успешно завершена. Оставьте отзыв!',
    createdAt: '2025-07-23T18:30:00Z',
    isRead: true,
    actionUrl: '/dev-ui/reviews',
    actionLabel: 'Оставить отзыв',
    image: null,
    meta: {
      itemTitle: 'Велосипед Trek Marlin 7',
      counterpartyName: 'Сергей Волков',
      dealStatus: 'COMPLETED',
      dealStatusLabel: 'Завершена',
    },
  },
  {
    id: 'ntf-006',
    type: 'deal_rejected',
    priority: 'normal',
    title: 'Заявка отклонена',
    body: 'Елена Морозова отклонила вашу заявку на «Палатка MSR Hubba Hubba». Причина: даты заняты другим арендатором.',
    createdAt: '2025-07-23T15:00:00Z',
    isRead: true,
    actionUrl: '/dev-ui/chat',
    image: null,
    meta: {
      itemTitle: 'Палатка MSR Hubba Hubba',
      counterpartyName: 'Елена Морозова',
      dealStatus: 'REJECTED',
      dealStatusLabel: 'Отклонена',
    },
  },
  {
    id: 'ntf-020',
    type: 'deal_cancelled',
    priority: 'high',
    title: 'Аренда отменена',
    body: 'Аренда «Проектор Epson EH-TW7100» была отменена. Средства вернутся в течение 24 часов.',
    createdAt: '2025-07-22T11:00:00Z',
    isRead: true,
    actionUrl: '/dev-ui/chat',
    image: null,
    meta: {
      itemTitle: 'Проектор Epson EH-TW7100',
      counterpartyName: 'Николай Фёдоров',
      dealStatus: 'REJECTED',
      dealStatusLabel: 'Отклонена',
    },
  },

  /* ═══ Платежи ═══ */
  {
    id: 'ntf-007',
    type: 'payment_received',
    priority: 'normal',
    title: 'Оплата получена',
    body: 'Вы получили 4 500 ₽ за аренду «Canon EOS R5». Средства зачислены на баланс.',
    createdAt: '2025-07-24T11:45:00Z',
    isRead: false,
    image: null,
    meta: {
      itemTitle: 'Canon EOS R5',
      amount: 4500,
      currency: '₽',
    },
  },
  {
    id: 'ntf-008',
    type: 'payment_sent',
    priority: 'normal',
    title: 'Оплата отправлена',
    body: 'Вы оплатили 3 500 ₽ за аренду «DJI Mavic 3 Pro». Квитанция доступна в истории.',
    createdAt: '2025-07-24T09:30:00Z',
    isRead: true,
    image: null,
    meta: {
      itemTitle: 'DJI Mavic 3 Pro',
      amount: 3500,
      currency: '₽',
    },
  },
  {
    id: 'ntf-009',
    type: 'deposit_held',
    priority: 'normal',
    title: 'Залог удержан',
    body: 'Залог 5 000 ₽ удержан за «Canon EOS R5». Будет возвращён после завершения аренды.',
    createdAt: '2025-07-24T09:00:00Z',
    isRead: true,
    image: null,
    meta: {
      itemTitle: 'Canon EOS R5',
      amount: 5000,
      currency: '₽',
    },
  },
  {
    id: 'ntf-010',
    type: 'deposit_returned',
    priority: 'normal',
    title: 'Залог возвращён',
    body: 'Залог 3 000 ₽ за «Велосипед Trek Marlin 7» возвращён на вашу карту. Зачисление 1–3 дня.',
    createdAt: '2025-07-23T19:00:00Z',
    isRead: true,
    image: null,
    meta: {
      itemTitle: 'Велосипед Trek Marlin 7',
      amount: 3000,
      currency: '₽',
    },
  },

  /* ═══ Отзывы ═══ */
  {
    id: 'ntf-011',
    type: 'review_received',
    priority: 'normal',
    title: 'Новый отзыв',
    body: 'Алексей Петров оставил отзыв на вашу аренду «DJI Mavic 3 Pro»: «Отличная камера, всё было идеально!»',
    createdAt: '2025-07-24T07:00:00Z',
    isRead: false,
    actionUrl: '/dev-ui/reviews',
    actionLabel: 'Посмотреть отзыв',
    image: null,
    meta: {
      counterpartyName: 'Алексей Петров',
      itemTitle: 'DJI Mavic 3 Pro',
      rating: 5,
    },
  },
  {
    id: 'ntf-012',
    type: 'review_reminder',
    priority: 'low',
    title: 'Оставьте отзыв',
    body: 'Аренда «Велосипед Trek Marlin 7» завершена 2 дня назад. Поделитесь впечатлениями — это поможет другим пользователям.',
    createdAt: '2025-07-23T10:00:00Z',
    isRead: true,
    actionUrl: '/dev-ui/reviews',
    actionLabel: 'Написать отзыв',
    image: null,
    meta: {
      itemTitle: 'Велосипед Trek Marlin 7',
      counterpartyName: 'Сергей Волков',
    },
  },

  /* ═══ Сообщения ═══ */
  {
    id: 'ntf-013',
    type: 'message_new',
    priority: 'normal',
    title: 'Новое сообщение',
    body: 'Мария Иванова: «Можно забрать камеру завтра утром в 10:00?»',
    createdAt: '2025-07-24T14:35:00Z',
    isRead: false,
    actionUrl: '/dev-ui/chat',
    image: null,
    meta: {
      counterpartyName: 'Мария Иванова',
      itemTitle: 'Canon EOS R5',
    },
  },
  {
    id: 'ntf-014',
    type: 'message_new',
    priority: 'normal',
    title: 'Новое сообщение',
    body: 'Дмитрий Козлов: «Консоль в отличном состоянии, спасибо!»',
    createdAt: '2025-07-24T10:20:00Z',
    isRead: true,
    actionUrl: '/dev-ui/chat',
    image: null,
    meta: {
      counterpartyName: 'Дмитрий Козлов',
      itemTitle: 'PlayStation 5 + VR2',
    },
  },
  {
    id: 'ntf-021',
    type: 'message_mention',
    priority: 'high',
    title: 'Вас упомянули',
    body: 'Ольга Смирнова упомянула вас в чате по сделке «Шуруповёрт Makita DDF484».',
    createdAt: '2025-07-23T16:30:00Z',
    isRead: false,
    actionUrl: '/dev-ui/chat',
    image: null,
    meta: {
      counterpartyName: 'Ольга Смирнова',
      itemTitle: 'Шуруповёрт Makita DDF484',
    },
  },

  /* ═══ Система & Безопасность ═══ */
  {
    id: 'ntf-015',
    type: 'verification',
    priority: 'high',
    title: 'Подтвердите email',
    body: 'Для полного доступа к платформе подтвердите ваш email-адрес. Письмо отправлено на v***@gmail.com.',
    createdAt: '2025-07-22T12:00:00Z',
    isRead: true,
    actionLabel: 'Подтвердить',
    image: null,
  },
  {
    id: 'ntf-016',
    type: 'security',
    priority: 'urgent',
    title: 'Вход с нового устройства',
    body: 'Зафиксирован вход в аккаунт с Windows 11 / Chrome (Москва). Если это не вы — смените пароль.',
    createdAt: '2025-07-24T06:00:00Z',
    isRead: false,
    actionUrl: '/dev-ui/settings',
    actionLabel: 'Проверить безопасность',
    image: null,
  },
  {
    id: 'ntf-017',
    type: 'promo',
    priority: 'low',
    title: 'Бонус за первую аренду',
    body: 'Поздравляем! Вы получили скидку 15% на первую аренду. Промокод: WELCOME15. Действует до 31 августа.',
    createdAt: '2025-07-21T10:00:00Z',
    isRead: true,
    image: null,
  },
  {
    id: 'ntf-018',
    type: 'system',
    priority: 'low',
    title: 'Обновление платформы',
    body: 'Мы добавили систему рейтингов и верификацию арендодателей. Узнайте подробнее в блоге.',
    createdAt: '2025-07-20T09:00:00Z',
    isRead: true,
    actionLabel: 'Подробнее',
    image: null,
  },
  {
    id: 'ntf-019',
    type: 'system',
    priority: 'low',
    title: 'Добро пожаловать в Арендай!',
    body: 'Ваш аккаунт создан. Заполните профиль и начните арендовать или сдавать вещи уже сегодня.',
    createdAt: '2025-07-15T08:00:00Z',
    isRead: true,
    actionUrl: '/dev-ui/profile',
    actionLabel: 'Заполнить профиль',
    image: null,
  },
];
