import type {
  ModerationQueueItem,
  Complaint,
  ModeratedReview,
  ComplaintComment,
} from './types';

/* ── Moderation Queue ────────────────────────────────────────────────────── */

export const mockModerationQueue: ModerationQueueItem[] = [
  {
    id: 'item-mod-1',
    ownerId: 'user-1',
    title: 'Электросамокат Xiaomi Mi Pro 2',
    itemDescription: 'Мощный электросамокат для городских поездок, пробег до 45 км.',
    city: 'Москва',
    pricePerDay: 1200,
    pricePerHour: 200,
    depositAmount: 5000,
    status: 'MODERATION',
    viewsCount: 0,
    mainPhotoUrl: null,
    photos: [],
    createdAt: '2026-05-06T10:30:00Z',
    ownerName: 'Алексей Петров',
    ownerPhone: '+7 999 123-45-67',
    submittedAt: '2026-05-06T10:30:00Z',
    photosCount: 4,
    category: { id: 1, categoryName: 'Транспорт', slug: 'transport', sortOrder: 1, isActive: true },
  },
  {
    id: 'item-mod-2',
    ownerId: 'user-2',
    title: 'Палатка туристическая 4-местная',
    itemDescription: 'Водонепроницаемая палатка для кемпинга, быстрая сборка.',
    city: 'Санкт-Петербург',
    pricePerDay: 800,
    pricePerHour: null,
    depositAmount: 3000,
    status: 'MODERATION',
    viewsCount: 0,
    mainPhotoUrl: null,
    photos: [],
    createdAt: '2026-05-05T14:20:00Z',
    ownerName: 'Мария Иванова',
    ownerPhone: '+7 916 222-33-44',
    submittedAt: '2026-05-05T14:20:00Z',
    photosCount: 6,
    category: { id: 2, categoryName: 'Туризм', slug: 'tourism', sortOrder: 2, isActive: true },
  },
  {
    id: 'item-mod-3',
    ownerId: 'user-3',
    title: 'Canon EOS R5 + объектив 24-70mm',
    itemDescription: 'Профессиональная камера для фото и видео, идеальное состояние.',
    city: 'Екатеринбург',
    pricePerDay: 3500,
    pricePerHour: 600,
    depositAmount: 15000,
    status: 'MODERATION',
    viewsCount: 0,
    mainPhotoUrl: null,
    photos: [],
    createdAt: '2026-05-05T09:15:00Z',
    ownerName: 'Дмитрий Козлов',
    ownerPhone: '+7 905 555-66-77',
    submittedAt: '2026-05-05T09:15:00Z',
    photosCount: 8,
    category: { id: 3, categoryName: 'Электроника', slug: 'electronics', sortOrder: 3, isActive: true },
  },
  {
    id: 'item-mod-4',
    ownerId: 'user-4',
    title: 'Дрель-шуруповёрт Bosch GSR 18V',
    itemDescription: 'Аккумуляторный шуруповёрт с двумя батареями и кейсом.',
    city: 'Новосибирск',
    pricePerDay: 500,
    pricePerHour: 100,
    depositAmount: 2000,
    status: 'MODERATION',
    viewsCount: 0,
    mainPhotoUrl: null,
    photos: [],
    createdAt: '2026-05-04T16:45:00Z',
    ownerName: 'Сергей Волков',
    ownerPhone: '+7 912 888-99-00',
    submittedAt: '2026-05-04T16:45:00Z',
    photosCount: 3,
    category: { id: 4, categoryName: 'Инструменты', slug: 'tools', sortOrder: 4, isActive: true },
  },
  {
    id: 'item-mod-5',
    ownerId: 'user-5',
    title: 'Сноуборд Burton Custom 158',
    itemDescription: 'Универсальный сноуборд для фрирайда и парка.',
    city: 'Казань',
    pricePerDay: 1500,
    pricePerHour: null,
    depositAmount: 8000,
    status: 'MODERATION',
    viewsCount: 0,
    mainPhotoUrl: null,
    photos: [],
    createdAt: '2026-05-04T11:00:00Z',
    ownerName: 'Наталья Смирнова',
    ownerPhone: '+7 927 111-22-33',
    submittedAt: '2026-05-04T11:00:00Z',
    photosCount: 5,
    category: { id: 5, categoryName: 'Спорт', slug: 'sport', sortOrder: 5, isActive: true },
  },
];

/* ── Complaints ──────────────────────────────────────────────────────────── */

export const mockComplaints: Complaint[] = [
  {
    id: 'cmp-1',
    target: 'item',
    targetId: 'item-42',
    targetTitle: 'Перфоратор Makita HR2470',
    reason: 'Недостоверное описание',
    description: 'Указан перфоратор Makita, но на фотографиях другая модель. Фото не соответствуют действительности.',
    priority: 'high',
    status: 'new',
    reporterId: 'user-10',
    reporterName: 'Ольга Кузнецова',
    createdAt: '2026-05-07T08:12:00Z',
  },
  {
    id: 'cmp-2',
    target: 'user',
    targetId: 'user-15',
    targetTitle: 'Пользователь: Иван Сидоров',
    reason: 'Мошенничество',
    description: 'Пользователь берёт залог и не возвращает вещи. Три случая за последний месяц.',
    priority: 'critical',
    status: 'in_review',
    reporterId: 'user-20',
    reporterName: 'Андрей Белов',
    createdAt: '2026-05-06T15:30:00Z',
  },
  {
    id: 'cmp-3',
    target: 'review',
    targetId: 'review-88',
    targetTitle: 'Отзыв на "Велосипед Giant Talon"',
    reason: 'Оскорбительный контент',
    description: 'Отзыв содержит нецензурную лексику и личные оскорбления в адрес владельца.',
    priority: 'medium',
    status: 'new',
    reporterId: 'user-5',
    reporterName: 'Елена Морозова',
    createdAt: '2026-05-06T12:45:00Z',
  },
  {
    id: 'cmp-4',
    target: 'item',
    targetId: 'item-67',
    targetTitle: 'Дрон DJI Mavic Air 2',
    reason: 'Запрещённая категория',
    description: 'Объявление о сдаче дрона в аренду без указания регистрации в реестре БВС.',
    priority: 'medium',
    status: 'resolved',
    reporterId: 'user-8',
    reporterName: 'Павел Жуков',
    createdAt: '2026-05-05T09:00:00Z',
    resolvedAt: '2026-05-06T10:00:00Z',
    moderatorComment: 'Владелец предоставил документы регистрации, объявление восстановлено.',
  },
  {
    id: 'cmp-5',
    target: 'item',
    targetId: 'item-91',
    targetTitle: 'Генератор бензиновый 5 кВт',
    reason: 'Спам/дубликат',
    description: 'Одно и то же объявление размещено 4 раза с незначительными изменениями.',
    priority: 'low',
    status: 'dismissed',
    reporterId: 'user-12',
    reporterName: 'Виктория Новикова',
    createdAt: '2026-05-04T18:22:00Z',
    resolvedAt: '2026-05-05T11:30:00Z',
    moderatorComment: 'Дубликаты удалены, оставлено одно активное объявление.',
  },
  {
    id: 'cmp-6',
    target: 'user',
    targetId: 'user-22',
    targetTitle: 'Пользователь: Кирилл Фёдоров',
    reason: 'Грубое общение',
    description: 'Пользователь хамит арендаторам в чате, есть скриншоты переписки.',
    priority: 'medium',
    status: 'new',
    reporterId: 'user-30',
    reporterName: 'Татьяна Егорова',
    createdAt: '2026-05-07T07:00:00Z',
  },
];

/* ── Reviews moderation ──────────────────────────────────────────────────── */

export const mockModeratedReviews: ModeratedReview[] = [
  {
    id: 'rev-1',
    dealId: 'deal-10',
    itemId: 'item-5',
    reviewerId: 'user-3',
    reviewedUserId: 'user-1',
    reviewType: 'renter_to_owner',
    rating: 1,
    text: 'Ужасное состояние вещи. Не соответствует описанию. Полный обман!',
    createdAt: '2026-05-06T18:00:00Z',
    updatedAt: '2026-05-06T18:00:00Z',
    reviewerName: 'Дмитрий Козлов',
    reviewedUserName: 'Алексей Петров',
    itemTitle: 'Электросамокат Xiaomi Mi Pro 2',
    isFlagged: true,
    flagReason: 'Возможный заказной негативный отзыв',
  },
  {
    id: 'rev-2',
    dealId: 'deal-15',
    itemId: 'item-12',
    reviewerId: 'user-7',
    reviewedUserId: 'user-4',
    reviewType: 'renter_to_owner',
    rating: 5,
    text: 'Отличный инструмент, всё как в описании. Владелец очень вежливый, рекомендую!',
    createdAt: '2026-05-05T12:00:00Z',
    updatedAt: '2026-05-05T12:00:00Z',
    reviewerName: 'Анна Лебедева',
    reviewedUserName: 'Сергей Волков',
    itemTitle: 'Дрель-шуруповёрт Bosch GSR 18V',
    isFlagged: false,
  },
  {
    id: 'rev-3',
    dealId: 'deal-22',
    itemId: 'item-8',
    reviewerId: 'user-11',
    reviewedUserId: 'user-2',
    reviewType: 'owner_to_renter',
    rating: 2,
    text: 'Арендатор вернул палатку в грязном состоянии с порванной сеткой. Не рекомендую.',
    createdAt: '2026-05-04T16:30:00Z',
    updatedAt: '2026-05-04T16:30:00Z',
    reviewerName: 'Мария Иванова',
    reviewedUserName: 'Роман Черных',
    itemTitle: 'Палатка туристическая 4-местная',
    isFlagged: true,
    flagReason: 'Конфликтная ситуация, требуется проверка',
  },
  {
    id: 'rev-4',
    dealId: 'deal-30',
    itemId: 'item-18',
    reviewerId: 'user-9',
    reviewedUserId: 'user-6',
    reviewType: 'renter_to_owner',
    rating: 4,
    text: 'Хороший велосипед, незначительные царапины, но в целом доволен.',
    createdAt: '2026-05-03T10:00:00Z',
    updatedAt: '2026-05-03T10:00:00Z',
    reviewerName: 'Кирилл Фёдоров',
    reviewedUserName: 'Наталья Смирнова',
    itemTitle: 'Велосипед Giant Talon 29',
    isFlagged: false,
  },
  {
    id: 'rev-5',
    dealId: 'deal-35',
    itemId: 'item-25',
    reviewerId: 'user-14',
    reviewedUserId: 'user-3',
    reviewType: 'renter_to_owner',
    rating: 3,
    text: 'Камера работает, но объектив оказался другой модели. Связаться с владельцем было сложно.',
    createdAt: '2026-05-02T14:15:00Z',
    updatedAt: '2026-05-02T14:15:00Z',
    reviewerName: 'Павел Жуков',
    reviewedUserName: 'Дмитрий Козлов',
    itemTitle: 'Canon EOS R5 + объектив 24-70mm',
    isFlagged: true,
    flagReason: 'Несоответствие описания товара',
  },
];

/* ── Complaint comments (timeline) ─────────────────────────────────────── */

export const mockComplaintComments: Record<string, ComplaintComment[]> = {
  'cmp-1': [
    { id: 'cc-1', author: 'Модератор Дмитрий', text: 'Запросил дополнительные фото у заявителя.', createdAt: '2026-05-07T10:00:00Z' },
  ],
  'cmp-2': [
    { id: 'cc-2', author: 'Модератор Дмитрий', text: 'Проверяю историю сделок пользователя. Действительно есть 3 случая невозврата.', createdAt: '2026-05-06T16:00:00Z' },
    { id: 'cc-3', author: 'Администратор', text: 'Подтверждаю. Необходимо заблокировать аккаунт и рассмотреть возврат средств пострадавшим.', createdAt: '2026-05-07T09:30:00Z' },
  ],
  'cmp-4': [
    { id: 'cc-4', author: 'Модератор Дмитрий', text: 'Связался с владельцем, запросил документы.', createdAt: '2026-05-05T14:00:00Z' },
    { id: 'cc-5', author: 'Модератор Дмитрий', text: 'Документы регистрации получены, проверены — всё в порядке.', createdAt: '2026-05-06T09:00:00Z' },
    { id: 'cc-6', author: 'Модератор Дмитрий', text: 'Объявление восстановлено. Жалоба закрыта.', createdAt: '2026-05-06T10:00:00Z' },
  ],
};
