import type {
  DashboardData,
  AdminUser,
  AdminListing,
  AdminDeal,
  AdminPayment,
  FinanceSummary,
  PlatformSettings,
  ActivityLogEntry,
  AnalyticsData,
  TodayActivity,
  AdminNotification,
} from './types';

/* ── Dashboard ───────────────────────────────────────────────────────────── */

export const mockDashboard: DashboardData = {
  stats: [
    { key: 'users', label: 'Пользователей', value: 12450, formatted: '12 450', trend: 8.2, trendLabel: 'за месяц', color: 'green' },
    { key: 'listings', label: 'Активных объявлений', value: 3842, formatted: '3 842', trend: 12.5, trendLabel: 'за месяц', color: 'blue' },
    { key: 'deals', label: 'Сделок за месяц', value: 1256, formatted: '1 256', trend: 5.3, trendLabel: 'vs прошлый', color: 'orange' },
    { key: 'revenue', label: 'Выручка за месяц', value: 2840000, formatted: '2 840 000 ₽', trend: 15.7, trendLabel: 'vs прошлый', color: 'purple' },
    { key: 'moderation', label: 'На модерации', value: 23, formatted: '23', trend: -30, trendLabel: 'vs вчера', color: 'red' },
  ],
  usersChart: [
    { label: 'Янв', value: 8200 },
    { label: 'Фев', value: 8900 },
    { label: 'Мар', value: 9600 },
    { label: 'Апр', value: 10400 },
    { label: 'Май', value: 11200 },
    { label: 'Июн', value: 12450 },
  ],
  dealsChart: [
    { label: 'Янв', value: 780 },
    { label: 'Фев', value: 890 },
    { label: 'Мар', value: 1020 },
    { label: 'Апр', value: 1150 },
    { label: 'Май', value: 1180 },
    { label: 'Июн', value: 1256 },
  ],
  revenueChart: [
    { label: 'Янв', value: 1800000 },
    { label: 'Фев', value: 2100000 },
    { label: 'Мар', value: 2300000 },
    { label: 'Апр', value: 2500000 },
    { label: 'Май', value: 2650000 },
    { label: 'Июн', value: 2840000 },
  ],
  recentDeals: [],
  topCategories: [
    { name: 'Электроника', count: 1240, revenue: 980000 },
    { name: 'Транспорт', count: 860, revenue: 720000 },
    { name: 'Инструменты', count: 620, revenue: 340000 },
    { name: 'Спорт', count: 540, revenue: 280000 },
    { name: 'Туризм', count: 380, revenue: 220000 },
  ],
};

/* ── Users ───────────────────────────────────────────────────────────────── */

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'user-1',
    email: 'alexey@mail.ru',
    phone: '+7 999 123-45-67',
    fullName: 'Алексей Петров',
    nickname: 'alexey_p',
    avatarUrl: null,
    role: 'user',
    isActive: true,
    createdAt: '2025-12-15T10:00:00Z',
    listingsCount: 12,
    dealsCount: 34,
  },
  {
    id: 'user-2',
    email: 'maria@gmail.com',
    phone: '+7 916 222-33-44',
    fullName: 'Мария Иванова',
    nickname: 'masha_iv',
    avatarUrl: null,
    role: 'user',
    isActive: true,
    createdAt: '2026-01-20T14:30:00Z',
    listingsCount: 8,
    dealsCount: 22,
  },
  {
    id: 'user-3',
    email: 'dmitry@yandex.ru',
    phone: '+7 905 555-66-77',
    fullName: 'Дмитрий Козлов',
    nickname: 'dm_kozlov',
    avatarUrl: null,
    role: 'moderator',
    isActive: true,
    createdAt: '2025-11-01T09:00:00Z',
    listingsCount: 3,
    dealsCount: 15,
  },
  {
    id: 'user-4',
    email: 'sergey@mail.ru',
    phone: '+7 912 888-99-00',
    fullName: 'Сергей Волков',
    nickname: 'sergey_v',
    avatarUrl: null,
    role: 'user',
    isActive: false,
    createdAt: '2026-02-10T11:15:00Z',
    listingsCount: 5,
    dealsCount: 8,
  },
  {
    id: 'user-5',
    email: 'natalia@gmail.com',
    phone: '+7 927 111-22-33',
    fullName: 'Наталья Смирнова',
    nickname: 'nata_s',
    avatarUrl: null,
    role: 'user',
    isActive: true,
    createdAt: '2026-03-05T16:00:00Z',
    listingsCount: 15,
    dealsCount: 42,
  },
  {
    id: 'user-6',
    email: 'admin@arendai.ru',
    phone: '+7 900 000-00-01',
    fullName: 'Администратор',
    nickname: 'admin',
    avatarUrl: null,
    role: 'admin',
    isActive: true,
    createdAt: '2025-10-01T08:00:00Z',
    listingsCount: 0,
    dealsCount: 0,
  },
  {
    id: 'user-7',
    email: 'olga@mail.ru',
    phone: '+7 903 444-55-66',
    fullName: 'Ольга Кузнецова',
    nickname: 'olga_k',
    avatarUrl: null,
    role: 'user',
    isActive: true,
    createdAt: '2026-04-12T13:45:00Z',
    listingsCount: 6,
    dealsCount: 18,
  },
  {
    id: 'user-8',
    email: 'ivan@yandex.ru',
    phone: '+7 911 777-88-99',
    fullName: 'Иван Сидоров',
    nickname: 'ivan_sid',
    avatarUrl: null,
    role: 'user',
    isActive: false,
    createdAt: '2026-01-08T10:30:00Z',
    listingsCount: 2,
    dealsCount: 3,
  },
];

/* ── Listings ────────────────────────────────────────────────────────────── */

export const mockAdminListings: AdminListing[] = [
  {
    id: 'item-1',
    ownerId: 'user-1',
    title: 'Электросамокат Xiaomi Mi Pro 2',
    itemDescription: 'Мощный электросамокат для городских поездок.',
    city: 'Москва',
    pricePerDay: 1200,
    pricePerHour: 200,
    depositAmount: 5000,
    status: 'ACTIVE',
    viewsCount: 342,
    mainPhotoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop',
    photos: [
      { id: 'ph-1a', photoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop', sortOrder: 0 },
      { id: 'ph-1b', photoUrl: 'https://images.unsplash.com/photo-1604868189007-90110939877b?w=800&h=600&fit=crop', sortOrder: 1 },
      { id: 'ph-1c', photoUrl: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop', sortOrder: 2 },
    ],
    createdAt: '2026-03-10T10:00:00Z',
    ownerName: 'Алексей Петров',
    ownerPhone: '+7 999 123-45-67',
    dealsCount: 18,
    revenue: 54000,
    category: { id: 1, categoryName: 'Транспорт', slug: 'transport', sortOrder: 1, isActive: true },
  },
  {
    id: 'item-2',
    ownerId: 'user-2',
    title: 'Палатка туристическая 4-местная',
    itemDescription: 'Водонепроницаемая палатка для кемпинга.',
    city: 'Санкт-Петербург',
    pricePerDay: 800,
    pricePerHour: null,
    depositAmount: 3000,
    status: 'ACTIVE',
    viewsCount: 215,
    mainPhotoUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop',
    photos: [
      { id: 'ph-2a', photoUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop', sortOrder: 0 },
      { id: 'ph-2b', photoUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&h=600&fit=crop', sortOrder: 1 },
    ],
    createdAt: '2026-02-20T14:00:00Z',
    ownerName: 'Мария Иванова',
    ownerPhone: '+7 916 222-33-44',
    dealsCount: 12,
    revenue: 28800,
    category: { id: 2, categoryName: 'Туризм', slug: 'tourism', sortOrder: 2, isActive: true },
  },
  {
    id: 'item-3',
    ownerId: 'user-3',
    title: 'Canon EOS R5 + объектив 24-70mm',
    itemDescription: 'Профессиональная камера.',
    city: 'Екатеринбург',
    pricePerDay: 3500,
    pricePerHour: 600,
    depositAmount: 15000,
    status: 'MODERATION',
    viewsCount: 0,
    mainPhotoUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop',
    photos: [
      { id: 'ph-3a', photoUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop', sortOrder: 0 },
      { id: 'ph-3b', photoUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop', sortOrder: 1 },
      { id: 'ph-3c', photoUrl: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop', sortOrder: 2 },
    ],
    createdAt: '2026-05-05T09:15:00Z',
    ownerName: 'Дмитрий Козлов',
    ownerPhone: '+7 905 555-66-77',
    dealsCount: 0,
    revenue: 0,
    category: { id: 3, categoryName: 'Электроника', slug: 'electronics', sortOrder: 3, isActive: true },
  },
  {
    id: 'item-4',
    ownerId: 'user-4',
    title: 'Дрель-шуруповёрт Bosch GSR 18V',
    itemDescription: 'Аккумуляторный шуруповёрт.',
    city: 'Новосибирск',
    pricePerDay: 500,
    pricePerHour: 100,
    depositAmount: 2000,
    status: 'REJECTED',
    moderationComment: 'Фотографии не соответствуют товару.',
    viewsCount: 0,
    mainPhotoUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&h=600&fit=crop',
    photos: [
      { id: 'ph-4a', photoUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&h=600&fit=crop', sortOrder: 0 },
      { id: 'ph-4b', photoUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&h=600&fit=crop', sortOrder: 1 },
    ],
    createdAt: '2026-04-28T16:45:00Z',
    ownerName: 'Сергей Волков',
    ownerPhone: '+7 912 888-99-00',
    dealsCount: 0,
    revenue: 0,
    category: { id: 4, categoryName: 'Инструменты', slug: 'tools', sortOrder: 4, isActive: true },
  },
  {
    id: 'item-5',
    ownerId: 'user-5',
    title: 'Сноуборд Burton Custom 158',
    itemDescription: 'Универсальный сноуборд.',
    city: 'Казань',
    pricePerDay: 1500,
    pricePerHour: null,
    depositAmount: 8000,
    status: 'ARCHIVED',
    viewsCount: 189,
    mainPhotoUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop',
    photos: [
      { id: 'ph-5a', photoUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop', sortOrder: 0 },
      { id: 'ph-5b', photoUrl: 'https://images.unsplash.com/photo-1522056615691-da7b8106c665?w=800&h=600&fit=crop', sortOrder: 1 },
    ],
    createdAt: '2026-01-15T11:00:00Z',
    ownerName: 'Наталья Смирнова',
    ownerPhone: '+7 927 111-22-33',
    dealsCount: 8,
    revenue: 36000,
    category: { id: 5, categoryName: 'Спорт', slug: 'sport', sortOrder: 5, isActive: true },
  },
  {
    id: 'item-6',
    ownerId: 'user-7',
    title: 'Проектор Epson EH-TW7100',
    itemDescription: 'Домашний проектор 4K.',
    city: 'Москва',
    pricePerDay: 2000,
    pricePerHour: 350,
    depositAmount: 10000,
    status: 'ACTIVE',
    viewsCount: 156,
    mainPhotoUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=600&fit=crop',
    photos: [
      { id: 'ph-6a', photoUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=600&fit=crop', sortOrder: 0 },
      { id: 'ph-6b', photoUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&h=600&fit=crop', sortOrder: 1 },
      { id: 'ph-6c', photoUrl: 'https://images.unsplash.com/photo-1585399058947-cd4d7b4f4065?w=800&h=600&fit=crop', sortOrder: 2 },
    ],
    createdAt: '2026-04-20T12:00:00Z',
    ownerName: 'Ольга Кузнецова',
    ownerPhone: '+7 903 444-55-66',
    dealsCount: 6,
    revenue: 24000,
    category: { id: 3, categoryName: 'Электроника', slug: 'electronics', sortOrder: 3, isActive: true },
  },
];

/* ── Deals ───────────────────────────────────────────────────────────────── */

export const mockAdminDeals: AdminDeal[] = [
  {
    id: 'deal-1',
    itemId: 'item-1',
    renterId: 'user-7',
    ownerId: 'user-1',
    startDate: '2026-05-10',
    endDate: '2026-05-13',
    pricingMode: 'daily',
    totalPrice: 3600,
    depositAmount: 5000,
    status: 'ACTIVE',
    createdAt: '2026-05-08T10:00:00Z',
    itemTitle: 'Электросамокат Xiaomi Mi Pro 2',
    renterName: 'Ольга Кузнецова',
    ownerName: 'Алексей Петров',
    history: [
      { id: 'h1', dealId: 'deal-1', oldStatus: null, newStatus: 'PENDING', changedBy: 'user-7', changeSource: 'user', comment: null, changedAt: '2026-05-08T10:00:00Z' },
      { id: 'h2', dealId: 'deal-1', oldStatus: 'PENDING', newStatus: 'CONFIRMED', changedBy: 'user-1', changeSource: 'user', comment: null, changedAt: '2026-05-08T12:30:00Z' },
      { id: 'h3', dealId: 'deal-1', oldStatus: 'CONFIRMED', newStatus: 'ACTIVE', changedBy: null, changeSource: 'system', comment: 'Автоматическая активация', changedAt: '2026-05-10T00:00:00Z' },
    ],
  },
  {
    id: 'deal-2',
    itemId: 'item-2',
    renterId: 'user-1',
    ownerId: 'user-2',
    startDate: '2026-05-05',
    endDate: '2026-05-07',
    pricingMode: 'daily',
    totalPrice: 1600,
    depositAmount: 3000,
    status: 'COMPLETED',
    createdAt: '2026-05-03T14:00:00Z',
    itemTitle: 'Палатка туристическая 4-местная',
    renterName: 'Алексей Петров',
    ownerName: 'Мария Иванова',
    history: [
      { id: 'h4', dealId: 'deal-2', oldStatus: null, newStatus: 'PENDING', changedBy: 'user-1', changeSource: 'user', comment: null, changedAt: '2026-05-03T14:00:00Z' },
      { id: 'h5', dealId: 'deal-2', oldStatus: 'PENDING', newStatus: 'CONFIRMED', changedBy: 'user-2', changeSource: 'user', comment: null, changedAt: '2026-05-03T16:00:00Z' },
      { id: 'h6', dealId: 'deal-2', oldStatus: 'CONFIRMED', newStatus: 'ACTIVE', changedBy: null, changeSource: 'system', comment: null, changedAt: '2026-05-05T00:00:00Z' },
      { id: 'h7', dealId: 'deal-2', oldStatus: 'ACTIVE', newStatus: 'COMPLETED', changedBy: null, changeSource: 'system', comment: null, changedAt: '2026-05-07T23:59:00Z' },
    ],
  },
  {
    id: 'deal-3',
    itemId: 'item-6',
    renterId: 'user-5',
    ownerId: 'user-7',
    startDate: '2026-05-15',
    endDate: '2026-05-17',
    pricingMode: 'daily',
    totalPrice: 4000,
    depositAmount: 10000,
    status: 'PENDING',
    createdAt: '2026-05-07T09:00:00Z',
    itemTitle: 'Проектор Epson EH-TW7100',
    renterName: 'Наталья Смирнова',
    ownerName: 'Ольга Кузнецова',
    history: [
      { id: 'h8', dealId: 'deal-3', oldStatus: null, newStatus: 'PENDING', changedBy: 'user-5', changeSource: 'user', comment: null, changedAt: '2026-05-07T09:00:00Z' },
    ],
  },
  {
    id: 'deal-4',
    itemId: 'item-1',
    renterId: 'user-2',
    ownerId: 'user-1',
    startDate: '2026-05-01',
    endDate: '2026-05-03',
    pricingMode: 'daily',
    totalPrice: 2400,
    depositAmount: 5000,
    status: 'REJECTED',
    rejectionReason: 'Самокат уже забронирован на эти даты.',
    createdAt: '2026-04-28T16:00:00Z',
    itemTitle: 'Электросамокат Xiaomi Mi Pro 2',
    renterName: 'Мария Иванова',
    ownerName: 'Алексей Петров',
    history: [
      { id: 'h9', dealId: 'deal-4', oldStatus: null, newStatus: 'PENDING', changedBy: 'user-2', changeSource: 'user', comment: null, changedAt: '2026-04-28T16:00:00Z' },
      { id: 'h10', dealId: 'deal-4', oldStatus: 'PENDING', newStatus: 'REJECTED', changedBy: 'user-1', changeSource: 'user', comment: 'Самокат уже забронирован', changedAt: '2026-04-29T08:00:00Z' },
    ],
  },
  {
    id: 'deal-5',
    itemId: 'item-5',
    renterId: 'user-3',
    ownerId: 'user-5',
    startDate: '2026-02-10',
    endDate: '2026-02-15',
    pricingMode: 'daily',
    totalPrice: 7500,
    depositAmount: 8000,
    status: 'CANCELLED',
    rejectionReason: 'Изменились планы арендатора.',
    createdAt: '2026-02-05T11:00:00Z',
    itemTitle: 'Сноуборд Burton Custom 158',
    renterName: 'Дмитрий Козлов',
    ownerName: 'Наталья Смирнова',
    history: [
      { id: 'h11', dealId: 'deal-5', oldStatus: null, newStatus: 'PENDING', changedBy: 'user-3', changeSource: 'user', comment: null, changedAt: '2026-02-05T11:00:00Z' },
      { id: 'h12', dealId: 'deal-5', oldStatus: 'PENDING', newStatus: 'CONFIRMED', changedBy: 'user-5', changeSource: 'user', comment: null, changedAt: '2026-02-05T15:00:00Z' },
      { id: 'h13', dealId: 'deal-5', oldStatus: 'CONFIRMED', newStatus: 'CANCELLED', changedBy: 'user-3', changeSource: 'user', comment: 'Изменились планы', changedAt: '2026-02-08T10:00:00Z' },
    ],
  },
];

/* ── Payments ────────────────────────────────────────────────────────────── */

export const mockAdminPayments: AdminPayment[] = [
  {
    paymentId: 'pay-1',
    dealId: 'deal-1',
    totalAmount: 8600,
    rentalAmount: 3600,
    depositAmount: 5000,
    status: 'CAPTURED',
    itemTitle: 'Электросамокат Xiaomi Mi Pro 2',
    renterName: 'Ольга Кузнецова',
    ownerName: 'Алексей Петров',
    createdAt: '2026-05-08T10:15:00Z',
  },
  {
    paymentId: 'pay-2',
    dealId: 'deal-2',
    totalAmount: 4600,
    rentalAmount: 1600,
    depositAmount: 3000,
    status: 'CAPTURED',
    itemTitle: 'Палатка туристическая 4-местная',
    renterName: 'Алексей Петров',
    ownerName: 'Мария Иванова',
    createdAt: '2026-05-03T14:30:00Z',
  },
  {
    paymentId: 'pay-3',
    dealId: 'deal-3',
    totalAmount: 14000,
    rentalAmount: 4000,
    depositAmount: 10000,
    status: 'PENDING',
    itemTitle: 'Проектор Epson EH-TW7100',
    renterName: 'Наталья Смирнова',
    ownerName: 'Ольга Кузнецова',
    createdAt: '2026-05-07T09:05:00Z',
  },
  {
    paymentId: 'pay-4',
    dealId: 'deal-5',
    totalAmount: 15500,
    rentalAmount: 7500,
    depositAmount: 8000,
    status: 'REFUNDED',
    itemTitle: 'Сноуборд Burton Custom 158',
    renterName: 'Дмитрий Козлов',
    ownerName: 'Наталья Смирнова',
    createdAt: '2026-02-05T11:30:00Z',
  },
  {
    paymentId: 'pay-5',
    dealId: 'deal-4',
    totalAmount: 7400,
    rentalAmount: 2400,
    depositAmount: 5000,
    status: 'CANCELED',
    itemTitle: 'Электросамокат Xiaomi Mi Pro 2',
    renterName: 'Мария Иванова',
    ownerName: 'Алексей Петров',
    createdAt: '2026-04-28T16:10:00Z',
  },
];

export const mockFinanceSummary: FinanceSummary = {
  totalRevenue: 2840000,
  totalDeposits: 1560000,
  pendingPayments: 14000,
  refundsTotal: 45200,
};

/* ── Platform settings ───────────────────────────────────────────────────── */

export const mockPlatformSettings: PlatformSettings = {
  commissionPercent: 10,
  minRentalHours: 4,
  maxDepositPercent: 50,
  autoApproveListings: false,
  maxPhotosPerListing: 10,
  maxListingsPerUser: 30,
  categories: [
    { id: 1, name: 'Транспорт', slug: 'transport', isActive: true, itemsCount: 860 },
    { id: 2, name: 'Туризм', slug: 'tourism', isActive: true, itemsCount: 380 },
    { id: 3, name: 'Электроника', slug: 'electronics', isActive: true, itemsCount: 1240 },
    { id: 4, name: 'Инструменты', slug: 'tools', isActive: true, itemsCount: 620 },
    { id: 5, name: 'Спорт', slug: 'sport', isActive: true, itemsCount: 540 },
    { id: 6, name: 'Одежда', slug: 'clothing', isActive: true, itemsCount: 290 },
    { id: 7, name: 'Дом и сад', slug: 'home', isActive: false, itemsCount: 45 },
  ],
};

/* ── Activity Log ──────────────────────────────────────────────────────── */

export const mockActivityLog: ActivityLogEntry[] = [
  {
    id: 'al-1',
    action: 'user_ban',
    actionLabel: 'Блокировка пользователя',
    targetType: 'user',
    targetId: 'user-4',
    targetTitle: 'Сергей Волков',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-08T09:15:00Z',
    details: 'Нарушение правил платформы',
  },
  {
    id: 'al-2',
    action: 'listing_archive',
    actionLabel: 'Снятие объявления',
    targetType: 'listing',
    targetId: 'item-12',
    targetTitle: 'Генератор бензиновый 5 кВт',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-08T08:30:00Z',
    details: 'Объявление не соответствует правилам',
  },
  {
    id: 'al-3',
    action: 'user_role_change',
    actionLabel: 'Смена роли',
    targetType: 'user',
    targetId: 'user-3',
    targetTitle: 'Дмитрий Козлов',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-07T16:45:00Z',
    details: 'Роль изменена на «Модератор»',
  },
  {
    id: 'al-4',
    action: 'deal_cancel',
    actionLabel: 'Отмена сделки',
    targetType: 'deal',
    targetId: 'deal-8',
    targetTitle: 'Сделка #8 — Проектор Epson',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-07T14:20:00Z',
    details: 'Мошенническая активность',
  },
  {
    id: 'al-5',
    action: 'payment_refund',
    actionLabel: 'Возврат платежа',
    targetType: 'payment',
    targetId: 'pay-6',
    targetTitle: 'Платёж #6 — 15 500 ₽',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-07T11:00:00Z',
  },
  {
    id: 'al-6',
    action: 'listing_approve',
    actionLabel: 'Одобрение объявления',
    targetType: 'listing',
    targetId: 'item-mod-1',
    targetTitle: 'Электросамокат Xiaomi Mi Pro 2',
    performedBy: 'user-3',
    performedByName: 'Дмитрий Козлов',
    performedAt: '2026-05-07T10:00:00Z',
  },
  {
    id: 'al-7',
    action: 'listing_reject',
    actionLabel: 'Отклонение объявления',
    targetType: 'listing',
    targetId: 'item-mod-4',
    targetTitle: 'Дрель-шуруповёрт Bosch GSR 18V',
    performedBy: 'user-3',
    performedByName: 'Дмитрий Козлов',
    performedAt: '2026-05-06T15:30:00Z',
    details: 'Фотографии не соответствуют товару',
  },
  {
    id: 'al-8',
    action: 'complaint_resolve',
    actionLabel: 'Решение жалобы',
    targetType: 'complaint',
    targetId: 'cmp-4',
    targetTitle: 'Жалоба на дрон DJI Mavic Air 2',
    performedBy: 'user-3',
    performedByName: 'Дмитрий Козлов',
    performedAt: '2026-05-06T10:00:00Z',
    details: 'Документы предоставлены, жалоба закрыта',
  },
  {
    id: 'al-9',
    action: 'review_delete',
    actionLabel: 'Удаление отзыва',
    targetType: 'review',
    targetId: 'rev-99',
    targetTitle: 'Отзыв на «Палатка туристическая»',
    performedBy: 'user-3',
    performedByName: 'Дмитрий Козлов',
    performedAt: '2026-05-05T17:00:00Z',
    details: 'Нецензурная лексика',
  },
  {
    id: 'al-10',
    action: 'settings_change',
    actionLabel: 'Изменение настроек',
    targetType: 'settings',
    targetId: 'settings',
    targetTitle: 'Комиссия платформы',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-05T09:00:00Z',
    details: 'Комиссия изменена с 8% на 10%',
  },
  {
    id: 'al-11',
    action: 'user_unban',
    actionLabel: 'Разблокировка пользователя',
    targetType: 'user',
    targetId: 'user-18',
    targetTitle: 'Елена Морозова',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-04T12:00:00Z',
  },
  {
    id: 'al-12',
    action: 'user_ban',
    actionLabel: 'Блокировка пользователя',
    targetType: 'user',
    targetId: 'user-8',
    targetTitle: 'Иван Сидоров',
    performedBy: 'admin',
    performedByName: 'Администратор',
    performedAt: '2026-05-03T14:30:00Z',
    details: 'Множественные жалобы от арендаторов',
  },
];

/* ── Analytics ─────────────────────────────────────────────────────────── */

export const mockAnalyticsData: AnalyticsData = {
  conversionRate: 3.2,
  conversionTrend: 0.4,
  averageCheck: 4250,
  averageCheckTrend: 8.1,
  retentionRate: 68,
  retentionTrend: 2.3,
  viewsToDeals: 1.8,
  viewsToDealsTrend: -0.3,
};

/* ── Today activity ────────────────────────────────────────────────────── */

export const mockTodayActivity: TodayActivity = {
  newRegistrations: 47,
  newListings: 18,
  newDeals: 32,
  newComplaints: 3,
};

/* ── Admin notifications ───────────────────────────────────────────────── */

export const mockAdminNotifications: AdminNotification[] = [
  {
    id: 'notif-1',
    title: 'Критическая жалоба',
    message: 'Новая жалоба на мошенничество требует немедленного рассмотрения',
    type: 'error',
    read: false,
    createdAt: '2026-05-08T09:00:00Z',
  },
  {
    id: 'notif-2',
    title: 'Новое объявление на модерации',
    message: '5 объявлений ожидают проверки более 2 часов',
    type: 'warning',
    read: false,
    createdAt: '2026-05-08T08:30:00Z',
  },
  {
    id: 'notif-3',
    title: 'Рекорд по сделкам',
    message: 'Сегодня заключено 32 сделки — новый рекорд для будней',
    type: 'success',
    read: false,
    createdAt: '2026-05-08T07:00:00Z',
  },
  {
    id: 'notif-4',
    title: 'Возврат оформлен',
    message: 'Возврат платежа #6 на сумму 15 500 ₽ обработан',
    type: 'info',
    read: true,
    createdAt: '2026-05-07T16:00:00Z',
  },
  {
    id: 'notif-5',
    title: 'Модератор добавлен',
    message: 'Дмитрий Козлов назначен модератором',
    type: 'info',
    read: true,
    createdAt: '2026-05-07T14:00:00Z',
  },
];
