import type { CatalogCardViewModel } from "./types";

export const mockCatalogItems: CatalogCardViewModel[] = [
  {
    id: "sony-a7iii",
    title: "Sony A7 III + Tamron 28–75",
    imageUrl:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Полнокадровая камера для съёмок, контента и путешествий. В комплекте аккумуляторы, карта памяти и удобная сумка.",
    price_per_day: "2900",
    price_per_hour: "450",
    deposit_amount: "5000",
    pickup_location: "Академгородок, Новосибирск",
    status: "active",
    views_count: 1842,
    created_at: "2026-04-02T10:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Фото и видео",
    ownerName: "Мария",
    ownerAvatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    rating: 4.9,
    reviewsCount: 28,
    instantBook: true,
    delivery: true,
    isNewArrival: true,
    featured: true,
    tags: ["4K", "Контент", "Портрет"],
  },
  {
    id: "dyson-v15",
    title: "Dyson V15 Detect для генеральной уборки",
    imageUrl:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Мощный беспроводной пылесос с насадками для квартиры, мебели и машины. Идеален для уборки перед сдачей квартиры или после ремонта.",
    price_per_day: "1200",
    price_per_hour: null,
    deposit_amount: "0",
    pickup_location: "ЖК Европейский берег",
    status: "active",
    views_count: 1260,
    created_at: "2026-03-29T10:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Для дома",
    ownerName: "Игорь",
    ownerAvatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    rating: 4.8,
    reviewsCount: 19,
    instantBook: true,
    delivery: false,
    isNewArrival: false,
    tags: ["Уборка", "Без залога", "Дом"],
  },
  {
    id: "nintendo-switch",
    title: "Nintendo Switch OLED + Mario Kart",
    imageUrl:
      "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Консоль для домашней вечеринки, поездки или уютных выходных. В комплекте чехол, зарядка и две игры.",
    price_per_day: "990",
    price_per_hour: "180",
    deposit_amount: "3000",
    pickup_location: "Площадь Ленина",
    status: "active",
    views_count: 2104,
    created_at: "2026-03-30T12:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Электроника",
    ownerName: "Артём",
    ownerAvatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80",
    rating: 4.7,
    reviewsCount: 34,
    instantBook: false,
    delivery: true,
    isNewArrival: false,
    tags: ["Игры", "Выходные", "OLED"],
  },
  {
    id: "makita-kit",
    title: "Набор инструментов Makita для ремонта",
    imageUrl:
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Шуруповёрт, перфоратор и набор бит для небольшого ремонта дома. Подойдёт для сборки мебели и монтажа полок.",
    price_per_day: "1500",
    price_per_hour: "250",
    deposit_amount: "3500",
    pickup_location: "Заельцовский район",
    status: "active",
    views_count: 987,
    created_at: "2026-03-27T08:00:00.000Z",
    location: "Новосибирск",
    isAvailable: false,
    dateAvailable: "2026-04-07",
    category: "Инструменты",
    ownerName: "Павел",
    ownerAvatar:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=300&q=80",
    rating: 4.6,
    reviewsCount: 12,
    instantBook: false,
    delivery: false,
    isNewArrival: false,
    tags: ["Ремонт", "DIY", "Мощный"],
  },
  {
    id: "sup-board",
    title: "SUP-борд для прогулок по воде",
    imageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Лёгкий надувной сапборд с насосом и рюкзаком. Отлично для пляжа, базы отдыха и коротких путешествий.",
    price_per_day: "1700",
    price_per_hour: null,
    deposit_amount: "4000",
    pickup_location: "ОбьГЭС",
    status: "active",
    views_count: 1398,
    created_at: "2026-04-01T09:00:00.000Z",
    location: "Бердск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Для спорта",
    ownerName: "Дарья",
    ownerAvatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80",
    rating: 5,
    reviewsCount: 17,
    instantBook: true,
    delivery: true,
    isNewArrival: true,
    tags: ["Лето", "Вода", "Выезд"],
  },
  {
    id: "projector",
    title: "Мини-проектор XGIMI для кино и презентаций",
    imageUrl:
      "https://images.unsplash.com/photo-1528395874238-34ebe249b3f2?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Компактный проектор с автофокусом и чистым звуком. Подходит для домашних кинопросмотров, игр и выездных презентаций.",
    price_per_day: "2100",
    price_per_hour: "320",
    deposit_amount: "4500",
    pickup_location: "Красный проспект",
    status: "active",
    views_count: 1765,
    created_at: "2026-03-31T15:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Электроника",
    ownerName: "Елена",
    ownerAvatar:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=300&q=80",
    rating: 4.8,
    reviewsCount: 23,
    instantBook: true,
    delivery: true,
    isNewArrival: false,
    featured: true,
    tags: ["Кино", "Презентации", "Full HD"],
  },
  {
    id: "camping-kit",
    title: "Туристический набор: палатка, стол, фонарь",
    imageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Готовый комплект для коротких выездов на природу. Всё уже собрано: палатка, походные кресла, фонарь и газовая горелка.",
    price_per_day: "2300",
    price_per_hour: null,
    deposit_amount: "5000",
    pickup_location: "Речной вокзал",
    status: "active",
    views_count: 1104,
    created_at: "2026-03-26T07:00:00.000Z",
    location: "Новосибирск",
    isAvailable: false,
    dateAvailable: "2026-04-10",
    category: "Путешествия",
    ownerName: "Кирилл",
    ownerAvatar:
      "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=300&q=80",
    rating: 4.9,
    reviewsCount: 15,
    instantBook: false,
    delivery: true,
    isNewArrival: false,
    tags: ["Кемпинг", "Выходные", "Комплект"],
  },
  {
    id: "ps5",
    title: "PlayStation 5 Slim с двумя геймпадами",
    imageUrl:
      "https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Консоль для вечеринок и домашних посиделок. Подходит для кооперативных игр и игровых вечеров в компании.",
    price_per_day: "1800",
    price_per_hour: "290",
    deposit_amount: "6000",
    pickup_location: "Студенческая",
    status: "active",
    views_count: 2450,
    created_at: "2026-04-03T11:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Электроника",
    ownerName: "Никита",
    ownerAvatar:
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=300&q=80",
    rating: 4.9,
    reviewsCount: 41,
    instantBook: true,
    delivery: false,
    isNewArrival: true,
    tags: ["Игры", "Вечеринка", "2 геймпада"],
  },
  {
    id: "gopro-hero12",
    title: "GoPro HERO12 для экшн-съёмок",
    imageUrl:
      "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Экшн-камера для велопрогулок, походов и съёмки контента. В комплекте крепления и стабилизирующий держатель.",
    price_per_day: "1450",
    price_per_hour: "220",
    deposit_amount: "3000",
    pickup_location: "Кольцово",
    status: "active",
    views_count: 1330,
    created_at: "2026-03-28T10:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Фото и видео",
    ownerName: "Софья",
    ownerAvatar:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80",
    rating: 4.7,
    reviewsCount: 22,
    instantBook: true,
    delivery: true,
    isNewArrival: false,
    tags: ["Экшн", "Путешествия", "Влог"],
  },
  {
    id: "soundbox",
    title: "Портативная колонка JBL PartyBox",
    imageUrl:
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Громкая колонка для домашних вечеринок, пикников и мероприятий. Работает долго, подключается моментально.",
    price_per_day: "1600",
    price_per_hour: "240",
    deposit_amount: "2500",
    pickup_location: "Октябрьская",
    status: "active",
    views_count: 1197,
    created_at: "2026-03-25T13:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Электроника",
    ownerName: "Владимир",
    ownerAvatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80",
    rating: 4.6,
    reviewsCount: 11,
    instantBook: false,
    delivery: true,
    isNewArrival: false,
    tags: ["Вечеринка", "Музыка", "Bluetooth"],
  },
  {
    id: "drill-bosch",
    title: "Bosch ударная дрель и набор сверл",
    imageUrl:
      "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Для ремонта, сборки мебели и бытовых задач по дому. Сумка, зарядка и набор сверл уже внутри кейса.",
    price_per_day: "900",
    price_per_hour: "150",
    deposit_amount: "0",
    pickup_location: "Первомайский район",
    status: "active",
    views_count: 842,
    created_at: "2026-04-01T17:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Инструменты",
    ownerName: "Алексей",
    ownerAvatar:
      "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=300&q=80",
    rating: 4.8,
    reviewsCount: 8,
    instantBook: true,
    delivery: false,
    isNewArrival: true,
    tags: ["Ремонт", "Без залога", "Дом"],
  },
  {
    id: "stroller",
    title: "Прогулочная коляска для путешествий",
    imageUrl:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Лёгкая складная коляска, которая подходит для коротких поездок, отпуска и прогулок по городу.",
    price_per_day: "800",
    price_per_hour: null,
    deposit_amount: "2000",
    pickup_location: "Площадь Маркса",
    status: "active",
    views_count: 954,
    created_at: "2026-03-24T06:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Путешествия",
    ownerName: "Анна",
    ownerAvatar:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
    rating: 4.9,
    reviewsCount: 14,
    instantBook: false,
    delivery: true,
    isNewArrival: false,
    tags: ["Дети", "Путешествия", "Компактная"],
  },
  {
    id: "tent-photo",
    title: "Свет для съёмки: 2 LED-панели + стойки",
    imageUrl:
      "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Набор света для студийных и предметных съёмок. Подходит для маркетплейсов, Reels и каталожных фотосессий.",
    price_per_day: "1300",
    price_per_hour: "200",
    deposit_amount: "2500",
    pickup_location: "Золотая Нива",
    status: "active",
    views_count: 1008,
    created_at: "2026-03-23T14:00:00.000Z",
    location: "Новосибирск",
    isAvailable: false,
    dateAvailable: "2026-04-06",
    category: "Фото и видео",
    ownerName: "Лиза",
    ownerAvatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    rating: 4.7,
    reviewsCount: 9,
    instantBook: false,
    delivery: false,
    isNewArrival: false,
    tags: ["Свет", "Студия", "Контент"],
  },
  {
    id: "treadmill",
    title: "Складная беговая дорожка для дома",
    imageUrl:
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80",
    item_description:
      "Компактная дорожка для тренировок дома. Подходит для восстановления режима и коротких кардио-сессий.",
    price_per_day: "1900",
    price_per_hour: null,
    deposit_amount: "5000",
    pickup_location: "МЖК Восточный",
    status: "active",
    views_count: 719,
    created_at: "2026-03-22T16:00:00.000Z",
    location: "Новосибирск",
    isAvailable: true,
    dateAvailable: "2026-04-04",
    category: "Для спорта",
    ownerName: "Виктор",
    ownerAvatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    rating: 4.5,
    reviewsCount: 6,
    instantBook: false,
    delivery: true,
    isNewArrival: false,
    tags: ["Кардио", "Дом", "Фитнес"],
  },
];
