import type { CatalogUiItem } from './types';

const makeDate = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

export const mockCatalogItems: CatalogUiItem[] = [
  {
    id: 'cam-sony-a7c',
    ownerId: null,
    categoryId: null,
    title: 'Nikon D3100 + 18-55mm для съёмок и поездок',
    coverImageUrl:
      'https://80.img.avito.st/image/1/1.IQ9A4ba4jeZ2Vg_rDqEiNXNBj-D-QA_wdk2P5PBIhez2.rTcnUszc63e9AvIduoimmMraH7WlUfiGfLeGOXmPKtk',
    images: [
      'https://80.img.avito.st/image/1/1.IQ9A4ba4jeZ2Vg_rDqEiNXNBj-D-QA_wdk2P5PBIhez2.rTcnUszc63e9AvIduoimmMraH7WlUfiGfLeGOXmPKtk',
      'https://20.img.avito.st/image/1/1.8gcq9raSSu4cQdzjQtm_PxlWHNuvYGzVrjRt1P80Pdj4YzjV_WVo1K02a93_ZWvbqjc57J5dXg.e9xyzj31QwUDSUZ1OXU4C6ln0xMoSPAxGYXB7i0RORs?cqp=2.1knsiTxPufH1SBh69vbZjVcwCORzzcj1-MOCwyWdGsPwNCmP_N-thpgCJLr6',
      'https://90.img.avito.st/image/1/1.ynF9v7aScphLCOSVZazIT04fJKqoLAau-CVXrK99Ba75fVP7-StSq_5_VaOufQGt8noBmskUZg.LEvdgLHl8HD4TCtzZH0PAb9WjPA8X2H5fdTVl73pEPA?',
      'https://sun9-60.userapi.com/s/v1/ig2/Bvpn_25A0s_i_3AE9Tjn3-8gtKwVpftvihaDKvKVdj2JY6JzUS0wZNGnzVs8Vdu5QMZub5tejH73yU8nVh85j2a8.jpg?quality=95&as=32x21,48x32,72x48,108x72,160x106,240x160,360x239,480x319,540x359,640x425,720x479,1080x718,1280x851,1440x957,2560x1702&from=bu&cs=2560x0',
    ],
    itemDescription:
      'Камера для тревел, контента и съёмок. Можно заснять аблакетку. В комплекте батарея, зарядник и сумка.',
    pricePerDay: '1000000',
    pricePerHour: '66666',
    depositAmount: '1,500,000',
    pickupLocation: 'м. Студенческая, самовывоз или курьер',
    status: 'ACTIVE',
    viewsCount: 382,
    createdAt: makeDate(1),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня с 14:00',
    category: 'Фото и видео',
    city: 'Новосибирск',
    ownerName: 'Санёк',
    ownerAvatar: 'А',
    ownerRating: 5,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 9 минут',
    tags: ['Проверенный арендодатель', 'Без доставки', 'APS-C'],
    pickupWindow: 'ежедневно 09:00–22:00',
    rentalTerms: [
      'Паспорт для договора аренды',
      'Проверка техники на месте выдачи',
      'Скидка 0,001% при аренде от 3 суток',
    ],
    specs: [
      { label: 'Матрица', value: '1024 МП' },
      { label: 'Видео', value: '8K 500fps' },
      { label: 'Вес', value: '509 г' },
      { label: 'Аккумулятор', value: '2 шт. в комплекте' },
    ],
    description: [
      'Отличный вариант для съёмки рилсов, интервью, мероприятий и поездок. Камера лёгкая, тихая и не привлекает лишнего внимания.',
      'В комплекте: б/у зарядка, китовый объектив-телескоп, 1 аккумулятор (на ядерном топливе), ремень чтоб драть кого-нибудь, карта памяти 128 ТБ и мешок на 120 литров с магнита.'
    ],
    featured: true,
    quickFilters: ['Рядом сегодня', 'Топ-рейтинг', 'Новинки'],
  },
  {
    id: 'ps5-white',
    ownerId: null,
    categoryId: null,
    title: 'PlayStation 5 Slim + 2 геймпада',
    coverImageUrl:
      'https://i.ytimg.com/vi/-eZbYhtsYgE/maxresdefault.jpg',
    images: [
      'https://i.ytimg.com/vi/-eZbYhtsYgE/maxresdefault.jpg',
      'https://static.tengrinews.kz/userdata/u289/2026-01/resize/1731a3374aeed431297670253364b758.jpg',
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription:
      'Для вечеринок и выходных: консоль, два геймпада, зарядная станция и подборка игр.',
    pricePerDay: '1800',
    pricePerHour: '300',
    depositAmount: '12000',
    pickupLocation: 'Заельцовский район',
    status: 'ACTIVE',
    viewsCount: 524,
    createdAt: makeDate(2),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Электроника',
    city: 'Новосибирск',
    ownerName: 'Мария',
    ownerAvatar: 'М',
    ownerRating: 5,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 5 минут',
    tags: ['С доставкой', 'Топ-рейтинг', 'Популярно'],
    pickupWindow: 'ежедневно 10:00–23:00',
    rentalTerms: [
      'Возврат в той же комплектации',
      'Можно арендовать на вечер',
      'Доставка по центру за 300 ₽',
    ],
    specs: [
      { label: 'Комплектация', value: '2 геймпада, зарядка' },
      { label: 'Память', value: '1 ТБ' },
      { label: 'Игры', value: 'EA FC, Mortal Kombat, It Takes Two' },
      { label: 'Режим', value: '4K / 120Hz' },
    ],
    description: [
      'Идеально для дружеских посиделок, романтического вечера дома или семейного уикенда.',
      'Консоль чистая, без шума, с готовым аккаунтом и установленными играми.'
    ],
    quickFilters: ['С доставкой', 'Топ-рейтинг', 'Рядом сегодня'],
  },
  {
    id: 'dyson-v15',
    ownerId: null,
    categoryId: null,
    title: 'Dyson V15 Detect для уборки квартиры',
    coverImageUrl:
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription:
      'Мощный беспроводной пылесос на генеральную уборку, переезд или клининг после ремонта.',
    pricePerDay: '900',
    pricePerHour: null,
    depositAmount: '5000',
    pickupLocation: 'Академгородок, Технопарк',
    status: 'ACTIVE',
    viewsCount: 214,
    createdAt: makeDate(4),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Завтра',
    category: 'Для дома',
    city: 'Академгородок',
    ownerName: 'Ирина',
    ownerAvatar: 'И',
    ownerRating: 4.8,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 18 минут',
    tags: ['Без залога', 'Проверено'],
    pickupWindow: 'будни 18:00–22:00',
    rentalTerms: ['Без животных шерсти внутри контейнера', 'Выдача после краткой демонстрации'],
    specs: [
      { label: 'Время работы', value: 'до 60 минут' },
      { label: 'Насадки', value: '4 шт.' },
      { label: 'Вес', value: '3 кг' },
      { label: 'Назначение', value: 'сухая уборка' },
    ],
    description: [
      'Часто берут на уборку после съёмной квартиры, перед переездом или после мелкого ремонта.',
      'Лазерная насадка хорошо показывает пыль на полу, удобно для быстрой глубокой уборки.'
    ],
    quickFilters: ['Без залога'],
  },
  {
    id: 'gopro-hero12',
    ownerId: null,
    categoryId: null,
    title: 'GoPro Hero 12 Black с креплениями',
    coverImageUrl:
      'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Экшн-камера для поездок, велопрогулок и воды. Есть крепление на грудь и селфи-ручка.',
    pricePerDay: '1200',
    pricePerHour: '250',
    depositAmount: '7000',
    pickupLocation: 'Кольцово',
    status: 'ACTIVE',
    viewsCount: 173,
    createdAt: makeDate(3),
    nearestAvailableDate: null,
    isAvailable: false,
    dateAvailable: 'Свободна с 12 апреля',
    category: 'Фото и видео',
    city: 'Кольцово',
    ownerName: 'Никита',
    ownerAvatar: 'Н',
    ownerRating: 4.7,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 25 минут',
    tags: ['Для путешествий'],
    pickupWindow: 'по договорённости',
    rentalTerms: ['Аренда от 1 суток', 'Возврат после зарядки аккумулятора'],
    specs: [
      { label: 'Видео', value: '5.3K' },
      { label: 'Защита', value: 'до 10 м без бокса' },
      { label: 'Аккумуляторы', value: '2 шт.' },
      { label: 'Комплект', value: 'крепления и кейс' },
    ],
    description: [
      'Отлично подходит для поездок на Алтай, съёмок на воде и активного отдыха.',
      'Есть базовая инструкция по настройке, могу помочь с первым запуском.'
    ],
    quickFilters: ['Новинки'],
  },
  {
    id: 'bosch-drill',
    ownerId: null,
    categoryId: null,
    title: 'Перфоратор Bosch + набор буров',
    coverImageUrl:
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581093588401-16ec548a9c2b?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Для домашнего ремонта, монтажа кухни и крепления карнизов. В кейсе и с расходниками.',
    pricePerDay: '700',
    pricePerHour: '180',
    depositAmount: '3000',
    pickupLocation: 'Бердск',
    status: 'ACTIVE',
    viewsCount: 321,
    createdAt: makeDate(5),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня после 18:00',
    category: 'Инструменты',
    city: 'Бердск',
    ownerName: 'Денис',
    ownerAvatar: 'Д',
    ownerRating: 4.6,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 14 минут',
    tags: ['Рядом сегодня', 'Без залога'],
    pickupWindow: 'ежедневно 08:00–21:00',
    rentalTerms: ['Есть удлинитель на 15 м', 'Можно взять вместе с шуруповёртом'],
    specs: [
      { label: 'Мощность', value: '800 Вт' },
      { label: 'Режимы', value: 'сверление / удар' },
      { label: 'Комплект', value: 'кейс + буры' },
      { label: 'Вес', value: '2.9 кг' },
    ],
    description: [
      'Практичный набор для ремонта без покупки дорогого инструмента.',
      'Инструмент обслужен, смазан и готов к работе.'
    ],
    quickFilters: ['Рядом сегодня', 'Без залога'],
  },
  {
    id: 'projector-xgimi',
    ownerId: null,
    categoryId: null,
    title: 'Проектор XGIMI MoGo 2 для вечера кино',
    coverImageUrl:
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Компактный проектор для фильмов, презентаций и домашних свиданий. Можно брать с экраном.',
    pricePerDay: '1500',
    pricePerHour: '250',
    depositAmount: '8000',
    pickupLocation: 'Новосибирск, Октябрьский район',
    status: 'ACTIVE',
    viewsCount: 447,
    createdAt: makeDate(2),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Электроника',
    city: 'Новосибирск',
    ownerName: 'Евгений',
    ownerAvatar: 'Е',
    ownerRating: 4.9,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 11 минут',
    tags: ['С доставкой', 'Для мероприятий'],
    pickupWindow: 'ежедневно 12:00–22:00',
    rentalTerms: ['Есть переносной экран 100 дюймов', 'Доставка по центру входит в цену от 2 суток'],
    specs: [
      { label: 'Яркость', value: '400 ISO люмен' },
      { label: 'Разрешение', value: 'Full HD' },
      { label: 'Звук', value: 'Harman/Kardon' },
      { label: 'Подключение', value: 'HDMI, Wi-Fi' },
    ],
    description: [
      'Часто арендуют для дней рождения, летних кинопоказов и презентаций.',
      'Очень простой в подключении, даю краткую памятку с настройкой.'
    ],
    featured: true,
    quickFilters: ['С доставкой', 'Топ-рейтинг'],
  },
  {
    id: 'tent-4p',
    ownerId: null,
    categoryId: null,
    title: 'Палатка 4-местная + спальники и коврики',
    coverImageUrl:
      'https://i.pinimg.com/736x/ac/f9/93/acf993143cfc6eefa0d19feeb861e8db.jpg',
    images: [
      'https://i.pinimg.com/736x/ac/f9/93/acf993143cfc6eefa0d19feeb861e8db.jpg',
      'https://i.pinimg.com/736x/74/e0/9d/74e09d8b982f659224b1df9274186b19.jpg',
    ],
    itemDescription: 'Набор для выезда на природу с друзьями или семьёй. Сухая и лёгкая сборка.',
    pricePerDay: '1600',
    pricePerHour: null,
    depositAmount: '4000',
    pickupLocation: 'Новосибирск, левый берег',
    status: 'ACTIVE',
    viewsCount: 288,
    createdAt: makeDate(6),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Свободна на выходные',
    category: 'Спорт и отдых',
    city: 'Новосибирск',
    ownerName: 'Саша',
    ownerAvatar: 'С',
    ownerRating: 4.8,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 17 минут',
    tags: ['Для путешествий', 'Без залога'],
    pickupWindow: 'пт–вс 07:00–23:00',
    rentalTerms: ['Возврат сухой и чистой', 'Можно добавить газовую горелку'],
    specs: [
      { label: 'Вместимость', value: '4 человека' },
      { label: 'Комплект', value: '2 спальника + 2 коврика' },
      { label: 'Вес', value: '6.4 кг' },
      { label: 'Сезон', value: 'весна–осень' },
    ],
    description: [
      'Хороший набор для первого похода или поездки на озеро без покупки своего туристического снаряжения.',
      'Возможен ранний выезд в пятницу утром.'
    ],
    quickFilters: ['Без залога'],
  },
  {
    id: 'stroller-bugaboo',
    ownerId: null,
    categoryId: null,
    title: 'Коляска Bugaboo Bee на прогулку и путешествия',
    coverImageUrl:
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516627145497-ae6968895b75?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Лёгкая складная коляска для поездок, отпуска, гостей с детьми и прогулок по городу.',
    pricePerDay: '1100',
    pricePerHour: null,
    depositAmount: '6000',
    pickupLocation: 'Новосибирск, Дзержинский район',
    status: 'ACTIVE',
    viewsCount: 167,
    createdAt: makeDate(7),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Детские товары',
    city: 'Новосибирск',
    ownerName: 'Лиза',
    ownerAvatar: 'Л',
    ownerRating: 4.9,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 8 минут',
    tags: ['С доставкой', 'Топ-рейтинг'],
    pickupWindow: 'ежедневно 09:00–21:00',
    rentalTerms: ['Чистая выдача, дождевик в комплекте', 'Есть адаптер под автокресло'],
    specs: [
      { label: 'Возраст', value: 'от 6 мес.' },
      { label: 'Вес коляски', value: '9.4 кг' },
      { label: 'Складывание', value: 'одной рукой' },
      { label: 'Комплект', value: 'дождевик, корзина' },
    ],
    description: [
      'Выручает в поездках, когда не хочется брать свою коляску или нужна запасная на неделю.',
      'Коляска обслужена и после химчистки.'
    ],
    quickFilters: ['С доставкой', 'Топ-рейтинг'],
  },
  {
    id: 'speaker-jbl-partybox',
    ownerId: null,
    categoryId: null,
    title: 'JBL PartyBox 310 для вечеринки и выезда',
    coverImageUrl:
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Мощная колонка с подсветкой для домашних вечеринок, праздников и выездов на природу.',
    pricePerDay: '2200',
    pricePerHour: '350',
    depositAmount: '10000',
    pickupLocation: 'Новосибирск, центр',
    status: 'ACTIVE',
    viewsCount: 458,
    createdAt: makeDate(3),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Мероприятия',
    city: 'Новосибирск',
    ownerName: 'Роман',
    ownerAvatar: 'Р',
    ownerRating: 4.9,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 6 минут',
    tags: ['С доставкой', 'Рядом сегодня'],
    pickupWindow: 'круглосуточно по брони',
    rentalTerms: ['Есть микрофон и стойка за доплату', 'Можно в аренду на 4 часа'],
    specs: [
      { label: 'Мощность', value: '240 Вт' },
      { label: 'Автономность', value: 'до 18 часов' },
      { label: 'Подключение', value: 'Bluetooth, AUX' },
      { label: 'Вес', value: '17.4 кг' },
    ],
    description: [
      'Самый частый сценарий — день рождения, барбекю на даче и выездные мероприятия.',
      'Колонка в хорошем состоянии, заряда хватает на полный вечер.'
    ],
    quickFilters: ['С доставкой', 'Рядом сегодня'],
  },
  {
    id: 'robot-lawn',
    ownerId: null,
    categoryId: null,
    title: 'Робот-газонокосилка Gardena на выходные',
    coverImageUrl:
      'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Для дачи, когда хочется быстро привести участок в порядок без покупки своей техники.',
    pricePerDay: '2300',
    pricePerHour: null,
    depositAmount: '10000',
    pickupLocation: 'Бердск, дачный массив',
    status: 'ACTIVE',
    viewsCount: 94,
    createdAt: makeDate(10),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'С пятницы',
    category: 'Для дома',
    city: 'Бердск',
    ownerName: 'Олег',
    ownerAvatar: 'О',
    ownerRating: 4.5,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 30 минут',
    tags: ['Новинки'],
    pickupWindow: 'по выходным',
    rentalTerms: ['Покажу настройку на месте', 'Есть удлинитель и запасной нож'],
    specs: [
      { label: 'Площадь', value: 'до 800 м²' },
      { label: 'Шум', value: 'тихий режим' },
      { label: 'Питание', value: 'аккумулятор' },
      { label: 'Комплект', value: 'станция и кабель' },
    ],
    description: [
      'Подходит для дач и частных домов, когда нужна аккуратная стрижка участка на выходные.',
      'Сдаётся с инструкцией и демонстрацией запуска.'
    ],
    quickFilters: ['Новинки'],
  },
  {
    id: 'sup-board',
    ownerId: null,
    categoryId: null,
    title: 'SUP-борд для прогулок по воде',
    coverImageUrl:
      'https://main-cdn.sbermegamarket.ru/big2/hlr-system/743/105/134/111/319/54/600022422559b1.jpg',
    images: [
      'https://main-cdn.sbermegamarket.ru/big2/hlr-system/743/105/134/111/319/54/600022422559b1.jpg',
      'https://main-cdn.sbermegamarket.ru/big2/hlr-system/-43/017/037/867/175/5/100032014797b8.jpg',
    ],
    itemDescription: 'Надувной SUP для прогулок, фотосессий и выездов на Обское море. Насос и жилет в комплекте.',
    pricePerDay: '1400',
    pricePerHour: null,
    depositAmount: '6000',
    pickupLocation: 'Новосибирск, ОбьГЭС',
    status: 'ACTIVE',
    viewsCount: 205,
    createdAt: makeDate(8),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'На эти выходные',
    category: 'Спорт и отдых',
    city: 'Новосибирск',
    ownerName: 'Вероника',
    ownerAvatar: 'В',
    ownerRating: 4.8,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 13 минут',
    tags: ['Для путешествий', 'Рядом сегодня'],
    pickupWindow: 'ежедневно 07:00–23:00',
    rentalTerms: ['Насос и гермомешок в комплекте', 'Можно арендовать два борда'],
    specs: [
      { label: 'Длина', value: '11 футов' },
      { label: 'Нагрузка', value: 'до 140 кг' },
      { label: 'Комплект', value: 'насос, весло, жилет' },
      { label: 'Сумка', value: 'есть' },
    ],
    description: [
      'Хороший вариант для летнего отдыха, прогулок на воде и фотосессий.',
      'Дам инструкцию по накачке и технике безопасности.'
    ],
    quickFilters: ['Рядом сегодня'],
  },
  {
    id: 'macbook-air',
    ownerId: null,
    categoryId: null,
    title: 'MacBook Air M2 для командировки и учёбы',
    coverImageUrl:
      'https://i.pinimg.com/originals/e9/16/c6/e916c6d5e940ac9de0c28325c217ae93.jpg?nii=t',
    images: [
      'https://i.pinimg.com/originals/e9/16/c6/e916c6d5e940ac9de0c28325c217ae93.jpg?nii=t',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
    ],
    itemDescription: 'Тонкий ноутбук для работы, презентаций и поездок. Зарядка и чехол в комплекте.',
    pricePerDay: '2800',
    pricePerHour: '500',
    depositAmount: '25000',
    pickupLocation: 'Новосибирск, метро Гагаринская',
    status: 'ACTIVE',
    viewsCount: 356,
    createdAt: makeDate(1),
    nearestAvailableDate: null,
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Электроника',
    city: 'Новосибирск',
    ownerName: 'Павел',
    ownerAvatar: 'П',
    ownerRating: 4.9,
    ownerReviewCount: null,
    itemRating: null,
    itemReviewCount: null,
    responseTime: 'отвечает за 7 минут',
    tags: ['Топ-рейтинг', 'С доставкой', 'Новинки'],
    pickupWindow: 'ежедневно 09:00–21:00',
    rentalTerms: ['Только по договору аренды', 'Можно арендовать с мышью и переходником HDMI'],
    specs: [
      { label: 'Экран', value: '13.6"' },
      { label: 'Процессор', value: 'Apple M2' },
      { label: 'Память', value: '16/512 ГБ' },
      { label: 'Автономность', value: 'до 14 часов' },
    ],
    description: [
      'Часто берут на конференции, командировки и короткие проекты, когда свой ноутбук в ремонте.',
      'Перед выдачей создаю чистый гостевой профиль и проверяю заряд.'
    ],
    quickFilters: ['С доставкой', 'Топ-рейтинг', 'Новинки'],
  },
];
