import type { CatalogUiItem } from './types';

const makeDate = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

export const mockCatalogItems: CatalogUiItem[] = [
  {
    id: 'cam-sony-a7c',
    title: 'Sony A7C + 28-60mm для съёмок и поездок',
    imageUrl:
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516724562728-afc824a36e84?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description:
      'Компактная full-frame камера для тревел, контента и съёмок интервью. В комплекте батареи и сумка.',
    price_per_day: '2500',
    price_per_hour: '450',
    deposit_amount: '15000',
    pickup_location: 'м. Площадь Ленина, самовывоз или курьер',
    status: 'active',
    views_count: 382,
    created_at: makeDate(1),
    location: 'Центральный район',
    isAvailable: true,
    dateAvailable: 'Сегодня с 14:00',
    category: 'Фото и видео',
    city: 'Новосибирск',
    ownerName: 'Артём',
    ownerAvatar: 'А',
    ownerRating: 4.9,
    responseTime: 'отвечает за 9 минут',
    tags: ['Проверенный арендодатель', 'Без доставки', 'Full-frame'],
    pickupWindow: 'ежедневно 09:00–22:00',
    rentalTerms: [
      'Паспорт для договора аренды',
      'Проверка техники на месте выдачи',
      'Скидка 10% при аренде от 3 суток',
    ],
    specs: [
      { label: 'Матрица', value: '24.2 МП' },
      { label: 'Видео', value: '4K 30fps' },
      { label: 'Вес', value: '509 г' },
      { label: 'Аккумулятор', value: '2 шт. в комплекте' },
    ],
    description: [
      'Отличный вариант для съёмки рилсов, интервью, мероприятий и поездок. Камера лёгкая, тихая и не привлекает лишнего внимания.',
      'В комплекте: тушка Sony A7C, китовый объектив 28-60mm, 2 аккумулятора, ремень, карта памяти 128 ГБ и сумка.'
    ],
    featured: true,
    quickFilters: ['Рядом сегодня', 'Топ-рейтинг', 'Новинки'],
  },
  {
    id: 'ps5-white',
    title: 'PlayStation 5 Slim + 2 геймпада',
    imageUrl:
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description:
      'Для вечеринок и выходных: консоль, два геймпада, зарядная станция и подборка игр.',
    price_per_day: '1800',
    price_per_hour: '300',
    deposit_amount: '12000',
    pickup_location: 'Заельцовский район',
    status: 'active',
    views_count: 524,
    created_at: makeDate(2),
    location: 'Заельцовский район',
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Электроника',
    city: 'Новосибирск',
    ownerName: 'Мария',
    ownerAvatar: 'М',
    ownerRating: 5,
    responseTime: 'отвечает за 5 минут',
    tags: ['С доставкой', 'Топ-рейтинг', 'Популярно'],
    pickupWindow: 'ежедневно 10:00–23:00',
    rentalTerms: [
      'Возврат в той же комплектации',
      'Можно арендовать на вечер',
      'Доставка по центру за 300 ₽',
    ],
    specs: [
      { label: 'Комплектация', value: '2 геймпада, зарядка' },
      { label: 'Память', value: '1 ТБ' },
      { label: 'Игры', value: 'EA FC, Mortal Kombat, It Takes Two' },
      { label: 'Режим', value: '4K / 120Hz' },
    ],
    description: [
      'Идеально для дружеских посиделок, романтического вечера дома или семейного уикенда.',
      'Консоль чистая, без шума, с готовым аккаунтом и установленными играми.'
    ],
    quickFilters: ['С доставкой', 'Топ-рейтинг', 'Рядом сегодня'],
  },
  {
    id: 'dyson-v15',
    title: 'Dyson V15 Detect для уборки квартиры',
    imageUrl:
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description:
      'Мощный беспроводной пылесос на генеральную уборку, переезд или клининг после ремонта.',
    price_per_day: '900',
    price_per_hour: null,
    deposit_amount: '5000',
    pickup_location: 'Академгородок, Технопарк',
    status: 'active',
    views_count: 214,
    created_at: makeDate(4),
    location: 'Академгородок',
    isAvailable: true,
    dateAvailable: 'Завтра',
    category: 'Для дома',
    city: 'Академгородок',
    ownerName: 'Ирина',
    ownerAvatar: 'И',
    ownerRating: 4.8,
    responseTime: 'отвечает за 18 минут',
    tags: ['Без залога', 'Проверено'],
    pickupWindow: 'будни 18:00–22:00',
    rentalTerms: ['Без животных шерсти внутри контейнера', 'Выдача после краткой демонстрации'],
    specs: [
      { label: 'Время работы', value: 'до 60 минут' },
      { label: 'Насадки', value: '4 шт.' },
      { label: 'Вес', value: '3 кг' },
      { label: 'Назначение', value: 'сухая уборка' },
    ],
    description: [
      'Часто берут на уборку после съёмной квартиры, перед переездом или после мелкого ремонта.',
      'Лазерная насадка хорошо показывает пыль на полу, удобно для быстрой глубокой уборки.'
    ],
    quickFilters: ['Без залога'],
  },
  {
    id: 'gopro-hero12',
    title: 'GoPro Hero 12 Black с креплениями',
    imageUrl:
      'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Экшн-камера для поездок, велопрогулок и воды. Есть крепление на грудь и селфи-ручка.',
    price_per_day: '1200',
    price_per_hour: '250',
    deposit_amount: '7000',
    pickup_location: 'Кольцово',
    status: 'active',
    views_count: 173,
    created_at: makeDate(3),
    location: 'Кольцово',
    isAvailable: false,
    dateAvailable: 'Свободна с 12 апреля',
    category: 'Фото и видео',
    city: 'Кольцово',
    ownerName: 'Никита',
    ownerAvatar: 'Н',
    ownerRating: 4.7,
    responseTime: 'отвечает за 25 минут',
    tags: ['Для путешествий'],
    pickupWindow: 'по договорённости',
    rentalTerms: ['Аренда от 1 суток', 'Возврат после зарядки аккумулятора'],
    specs: [
      { label: 'Видео', value: '5.3K' },
      { label: 'Защита', value: 'до 10 м без бокса' },
      { label: 'Аккумуляторы', value: '2 шт.' },
      { label: 'Комплект', value: 'крепления и кейс' },
    ],
    description: [
      'Отлично подходит для поездок на Алтай, съёмок на воде и активного отдыха.',
      'Есть базовая инструкция по настройке, могу помочь с первым запуском.'
    ],
    quickFilters: ['Новинки'],
  },
  {
    id: 'bosch-drill',
    title: 'Перфоратор Bosch + набор буров',
    imageUrl:
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581093588401-16ec548a9c2b?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Для домашнего ремонта, монтажа кухни и крепления карнизов. В кейсе и с расходниками.',
    price_per_day: '700',
    price_per_hour: '180',
    deposit_amount: '3000',
    pickup_location: 'Бердск',
    status: 'active',
    views_count: 321,
    created_at: makeDate(5),
    location: 'Бердск',
    isAvailable: true,
    dateAvailable: 'Сегодня после 18:00',
    category: 'Инструменты',
    city: 'Бердск',
    ownerName: 'Денис',
    ownerAvatar: 'Д',
    ownerRating: 4.6,
    responseTime: 'отвечает за 14 минут',
    tags: ['Рядом сегодня', 'Без залога'],
    pickupWindow: 'ежедневно 08:00–21:00',
    rentalTerms: ['Есть удлинитель на 15 м', 'Можно взять вместе с шуруповёртом'],
    specs: [
      { label: 'Мощность', value: '800 Вт' },
      { label: 'Режимы', value: 'сверление / удар' },
      { label: 'Комплект', value: 'кейс + буры' },
      { label: 'Вес', value: '2.9 кг' },
    ],
    description: [
      'Практичный набор для ремонта без покупки дорогого инструмента.',
      'Инструмент обслужен, смазан и готов к работе.'
    ],
    quickFilters: ['Рядом сегодня', 'Без залога'],
  },
  {
    id: 'projector-xgimi',
    title: 'Проектор XGIMI MoGo 2 для вечера кино',
    imageUrl:
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Компактный проектор для фильмов, презентаций и домашних свиданий. Можно брать с экраном.',
    price_per_day: '1500',
    price_per_hour: '250',
    deposit_amount: '8000',
    pickup_location: 'Новосибирск, Октябрьский район',
    status: 'active',
    views_count: 447,
    created_at: makeDate(2),
    location: 'Октябрьский район',
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Электроника',
    city: 'Новосибирск',
    ownerName: 'Евгений',
    ownerAvatar: 'Е',
    ownerRating: 4.9,
    responseTime: 'отвечает за 11 минут',
    tags: ['С доставкой', 'Для мероприятий'],
    pickupWindow: 'ежедневно 12:00–22:00',
    rentalTerms: ['Есть переносной экран 100 дюймов', 'Доставка по центру входит в цену от 2 суток'],
    specs: [
      { label: 'Яркость', value: '400 ISO люмен' },
      { label: 'Разрешение', value: 'Full HD' },
      { label: 'Звук', value: 'Harman/Kardon' },
      { label: 'Подключение', value: 'HDMI, Wi-Fi' },
    ],
    description: [
      'Часто арендуют для дней рождения, летних кинопоказов и презентаций.',
      'Очень простой в подключении, даю краткую памятку с настройкой.'
    ],
    featured: true,
    quickFilters: ['С доставкой', 'Топ-рейтинг'],
  },
  {
    id: 'tent-4p',
    title: 'Палатка 4-местная + спальники и коврики',
    imageUrl:
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Набор для выезда на природу с друзьями или семьёй. Сухая и лёгкая сборка.',
    price_per_day: '1600',
    price_per_hour: null,
    deposit_amount: '4000',
    pickup_location: 'Новосибирск, левый берег',
    status: 'active',
    views_count: 288,
    created_at: makeDate(6),
    location: 'Кировский район',
    isAvailable: true,
    dateAvailable: 'Свободна на выходные',
    category: 'Спорт и отдых',
    city: 'Новосибирск',
    ownerName: 'Саша',
    ownerAvatar: 'С',
    ownerRating: 4.8,
    responseTime: 'отвечает за 17 минут',
    tags: ['Для путешествий', 'Без залога'],
    pickupWindow: 'пт–вс 07:00–23:00',
    rentalTerms: ['Возврат сухой и чистой', 'Можно добавить газовую горелку'],
    specs: [
      { label: 'Вместимость', value: '4 человека' },
      { label: 'Комплект', value: '2 спальника + 2 коврика' },
      { label: 'Вес', value: '6.4 кг' },
      { label: 'Сезон', value: 'весна–осень' },
    ],
    description: [
      'Хороший набор для первого похода или поездки на озеро без покупки своего туристического снаряжения.',
      'Возможен ранний выезд в пятницу утром.'
    ],
    quickFilters: ['Без залога'],
  },
  {
    id: 'stroller-bugaboo',
    title: 'Коляска Bugaboo Bee на прогулку и путешествия',
    imageUrl:
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516627145497-ae6968895b75?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Лёгкая складная коляска для поездок, отпуска, гостей с детьми и прогулок по городу.',
    price_per_day: '1100',
    price_per_hour: null,
    deposit_amount: '6000',
    pickup_location: 'Новосибирск, Дзержинский район',
    status: 'active',
    views_count: 167,
    created_at: makeDate(7),
    location: 'Дзержинский район',
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Детские товары',
    city: 'Новосибирск',
    ownerName: 'Лиза',
    ownerAvatar: 'Л',
    ownerRating: 4.9,
    responseTime: 'отвечает за 8 минут',
    tags: ['С доставкой', 'Топ-рейтинг'],
    pickupWindow: 'ежедневно 09:00–21:00',
    rentalTerms: ['Чистая выдача, дождевик в комплекте', 'Есть адаптер под автокресло'],
    specs: [
      { label: 'Возраст', value: 'от 6 мес.' },
      { label: 'Вес коляски', value: '9.4 кг' },
      { label: 'Складывание', value: 'одной рукой' },
      { label: 'Комплект', value: 'дождевик, корзина' },
    ],
    description: [
      'Выручает в поездках, когда не хочется брать свою коляску или нужна запасная на неделю.',
      'Коляска обслужена и после химчистки.'
    ],
    quickFilters: ['С доставкой', 'Топ-рейтинг'],
  },
  {
    id: 'speaker-jbl-partybox',
    title: 'JBL PartyBox 310 для вечеринки и выезда',
    imageUrl:
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Мощная колонка с подсветкой для домашних вечеринок, праздников и выездов на природу.',
    price_per_day: '2200',
    price_per_hour: '350',
    deposit_amount: '10000',
    pickup_location: 'Новосибирск, центр',
    status: 'active',
    views_count: 458,
    created_at: makeDate(3),
    location: 'Центральный район',
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Мероприятия',
    city: 'Новосибирск',
    ownerName: 'Роман',
    ownerAvatar: 'Р',
    ownerRating: 4.9,
    responseTime: 'отвечает за 6 минут',
    tags: ['С доставкой', 'Рядом сегодня'],
    pickupWindow: 'круглосуточно по брони',
    rentalTerms: ['Есть микрофон и стойка за доплату', 'Можно в аренду на 4 часа'],
    specs: [
      { label: 'Мощность', value: '240 Вт' },
      { label: 'Автономность', value: 'до 18 часов' },
      { label: 'Подключение', value: 'Bluetooth, AUX' },
      { label: 'Вес', value: '17.4 кг' },
    ],
    description: [
      'Самый частый сценарий — день рождения, барбекю на даче и выездные мероприятия.',
      'Колонка в хорошем состоянии, заряда хватает на полный вечер.'
    ],
    quickFilters: ['С доставкой', 'Рядом сегодня'],
  },
  {
    id: 'robot-lawn',
    title: 'Робот-газонокосилка Gardena на выходные',
    imageUrl:
      'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Для дачи, когда хочется быстро привести участок в порядок без покупки своей техники.',
    price_per_day: '2300',
    price_per_hour: null,
    deposit_amount: '10000',
    pickup_location: 'Бердск, дачный массив',
    status: 'active',
    views_count: 94,
    created_at: makeDate(10),
    location: 'Бердск',
    isAvailable: true,
    dateAvailable: 'С пятницы',
    category: 'Для дома',
    city: 'Бердск',
    ownerName: 'Олег',
    ownerAvatar: 'О',
    ownerRating: 4.5,
    responseTime: 'отвечает за 30 минут',
    tags: ['Новинки'],
    pickupWindow: 'по выходным',
    rentalTerms: ['Покажу настройку на месте', 'Есть удлинитель и запасной нож'],
    specs: [
      { label: 'Площадь', value: 'до 800 м²' },
      { label: 'Шум', value: 'тихий режим' },
      { label: 'Питание', value: 'аккумулятор' },
      { label: 'Комплект', value: 'станция и кабель' },
    ],
    description: [
      'Подходит для дач и частных домов, когда нужна аккуратная стрижка участка на выходные.',
      'Сдаётся с инструкцией и демонстрацией запуска.'
    ],
    quickFilters: ['Новинки'],
  },
  {
    id: 'sup-board',
    title: 'SUP-борд для прогулок по воде',
    imageUrl:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Надувной SUP для прогулок, фотосессий и выездов на Обское море. Насос и жилет в комплекте.',
    price_per_day: '1400',
    price_per_hour: null,
    deposit_amount: '6000',
    pickup_location: 'Новосибирск, ОбьГЭС',
    status: 'active',
    views_count: 205,
    created_at: makeDate(8),
    location: 'Советский район',
    isAvailable: true,
    dateAvailable: 'На эти выходные',
    category: 'Спорт и отдых',
    city: 'Новосибирск',
    ownerName: 'Вероника',
    ownerAvatar: 'В',
    ownerRating: 4.8,
    responseTime: 'отвечает за 13 минут',
    tags: ['Для путешествий', 'Рядом сегодня'],
    pickupWindow: 'ежедневно 07:00–23:00',
    rentalTerms: ['Насос и гермомешок в комплекте', 'Можно арендовать два борда'],
    specs: [
      { label: 'Длина', value: '11 футов' },
      { label: 'Нагрузка', value: 'до 140 кг' },
      { label: 'Комплект', value: 'насос, весло, жилет' },
      { label: 'Сумка', value: 'есть' },
    ],
    description: [
      'Хороший вариант для летнего отдыха, прогулок на воде и фотосессий.',
      'Дам инструкцию по накачке и технике безопасности.'
    ],
    quickFilters: ['Рядом сегодня'],
  },
  {
    id: 'macbook-air',
    title: 'MacBook Air M2 для командировки и учёбы',
    imageUrl:
      'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
    ],
    item_description: 'Тонкий ноутбук для работы, презентаций и поездок. Зарядка и чехол в комплекте.',
    price_per_day: '2800',
    price_per_hour: '500',
    deposit_amount: '25000',
    pickup_location: 'Новосибирск, метро Гагаринская',
    status: 'active',
    views_count: 356,
    created_at: makeDate(1),
    location: 'Железнодорожный район',
    isAvailable: true,
    dateAvailable: 'Сегодня',
    category: 'Электроника',
    city: 'Новосибирск',
    ownerName: 'Павел',
    ownerAvatar: 'П',
    ownerRating: 4.9,
    responseTime: 'отвечает за 7 минут',
    tags: ['Топ-рейтинг', 'С доставкой', 'Новинки'],
    pickupWindow: 'ежедневно 09:00–21:00',
    rentalTerms: ['Только по договору аренды', 'Можно арендовать с мышью и переходником HDMI'],
    specs: [
      { label: 'Экран', value: '13.6"' },
      { label: 'Процессор', value: 'Apple M2' },
      { label: 'Память', value: '16/512 ГБ' },
      { label: 'Автономность', value: 'до 14 часов' },
    ],
    description: [
      'Часто берут на конференции, командировки и короткие проекты, когда свой ноутбук в ремонте.',
      'Перед выдачей создаю чистый гостевой профиль и проверяю заряд.'
    ],
    quickFilters: ['С доставкой', 'Топ-рейтинг', 'Новинки'],
  },
];
